### ISSUE TITLE
Error running HADashboard (right after installation via pip3)

### ISSUE THREAD

**Issue by Leon99** [home-assistant/appdaemon#136]
`pi@hassbian:~ $ appdaemon -c /home/homeassistant/.homeassistant/hadashboard`:
```
2017-09-10 10:15:35.381310 INFO AppDaemon Version 2.1.9 starting
2017-09-10 10:15:35.382300 INFO Configuration read from: /home/homeassistant/.homeassistant/hadashboard/appdaemon.yaml Traceback (most recent call last):
  File "/usr/local/bin/appdaemon", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/appdaemon/admain.py", line 478, in main
    conf.app_config_file_modified = os.path.getmtime(conf.app_config_file)
  File "/usr/lib/python3.4/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/homeassistant/.homeassistant/hadashboard/apps.yaml'
```

appdaemon.yaml:
```
AppDaemon:
  threads: 10
HASS:
  ha_url: http://192.168.1.40:8123
  ha_key: xxx
HADashboard:
  dash_url: http://192.168.1.40:5050
```

**Comment by acockburn** [comment]
This is a known issue for dashboard only users - you just need to create an empty apps.yaml file in the config directory.

**Comment by Leon99** [comment]
Thanks @acockburn, that helped. BTW I also had to create /compiled and its subdirs manually - is it a known issue as well?
I wonder if it's going to be fixed soon or is a something worth noting in the documentation? I think most of AppDaemon users use HADashboard only.
