### ISSUE TITLE
Incorrect references throw an exception

### ISSUE THREAD

**Issue by bachya** [home-assistant/appdaemon#137]
I'm getting this in the logs:

```
2017-09-12 16:37:52.694274 ERROR The following modules have unresolved dependencies:
Traceback (most recent call last):
  File "/usr/bin/appdaemon", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/appdaemon/appdaemon.py", line 1882, in main
    run()
  File "/usr/lib/python3.5/site-packages/appdaemon/appdaemon.py", line 1200, in run
    read_apps(True)
  File "/usr/lib/python3.5/site-packages/appdaemon/appdaemon.py", line 1058, in read_apps
    ha.log(conf.logger, "ERROR",  get_module_from_path(module["file"]))
KeyError: 'file'
```

Because of this exception, I can't find the module that has incorrect dependencies. :(

**Comment by acockburn** [comment]
I am guessing you missed a module or class directive fro one of your apps.

**Comment by joebetsill** [comment]
If you're running on a Raspbian setup, you probably didn't notice the very last section of the [installation guide.](https://appdaemon.readthedocs.io/en/latest/INSTALL.html)
Try:
`sudo apt-get install python dev`
`sudo apt-get install libffi-dev`
