### ISSUE TITLE
request meet aiohttp exception

### ISSUE THREAD

**Issue by rainmote** [home-assistant/appdaemon#152]
run `appdaemon -c /root/conf -D DEBUG`, I still have this problem when I change a computer.
Error Log
```
2017-09-30 22:55:11.424698 INFO hello_world: You are now ready to run Apps!
2017-09-30 22:55:11.424870 INFO App initialization complete
2017-09-30 22:55:11.424951 DEBUG Starting timer loop
2017-09-30 22:55:11.425135 INFO Starting dashboard
2017-09-30 22:55:11.428497 INFO Starting API
2017-09-30 22:55:11.429677 DEBUG Start Loop
2017-09-30 22:55:13.255812 INFO Connected to Home Assistant 0.54.0
2017-09-30 22:55:14.001609 WARNING Scheduler clock skew detected - delta = 2.0015029907226562 - resetting
2017-09-30 22:55:15.010297 DEBUG Main loop compute time: 6.0ms
……
2017-09-30 22:55:31.008558 DEBUG Main loop compute time: 5.0ms
2017-09-30 22:55:32.007983 DEBUG Main loop compute time: 5.0ms
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_protocol.py", line 422, in start
    resp = yield from self._request_handler(request)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/web.py", line 312, in _handle
    [middleware for middleware in app.middlewares
AssertionError: Handler <function secure.<locals>.wrapper at 0x7f49623306a8> should return response instance, got <class 'dict'> [middlewares []]
2017-09-30 22:55:33.009711 DEBUG Main loop compute time: 5.0ms
2017-09-30 22:55:34.007979 DEBUG Main loop compute time: 5.0ms
```

**Comment by rainmote** [comment]
appdaemon.yaml content:
```
AppDaemon:
  disable_apps: 1
  logfile: STDOUT
  errorfile: STDERR
  logsize: 100000
  log_generations: 3
  threads: 10
  #cert_path: /etc/letsencrypt/live/xxxx
  cert_verify: False
  api_port: 5000
  api_key: !secret appdaemon_key
  #api_ssl_certificate: /etc/letsencrypt/live/xxxx
  #api_ssl_key: /etc/letsencrypt/live/xxxx
HASS:
  ha_url: "https://xxxx:8123"
  ha_key: "xxxxxx"
HADashboard:
  dash_url: "http://xxxxx:5050"
  dash_password: !secret dash_key
  dash_dir: /conf/dashboards
  dash_force_compile: 1
  dash_compile_on_start: 1
  accessfile: /var/log/dash_access
```

**Comment by cryptooth** [comment]
Same issue after upgrading python 3.4 to 3.6 on Homeassistnat AIO setup.

**Comment by acockburn** [comment]
Does this affect any of the functionality or is it just cosmetic?

**Comment by dbarentine** [comment]
When I ran into that same stack trace on my instance it was causing a 500 error. I found this: https://community.home-assistant.io/t/hadashboard-dash-password-directive-causing-500-internal-server-error/29267

Removing dash_password from the configuration resolved it.

**Comment by acockburn** [comment]
OK, cool - I'll close this as I already have the password issue on my list to fix - thanks.
