### ISSUE TITLE
switch_reset.py fails to start due to import globals error

### ISSUE THREAD

**Issue by mad-ady** [home-assistant/appdaemon#156]
I'm trying to use the switch_reset.py app from the example_apps directory (I downloaded it from github). 
I'm using appdaemon supplied via pip3 (version 2.1.9):
```
adrianp@jumphost:~_ sudo pip3 show appdaemon
---
Metadata-Version: 2.0
Name: appdaemon
Version: 2.1.9
Summary: Apps for the Home Assistant home automation package.
Home-page: https://github.com/home-assistant/appdaemon.git
Author: Andrew I Cockburn
Author-email: appdaemon@acockburn.com
Installer: pip
License: Apache License 2.0
Location: /usr/local/lib/python3.5/dist-packages
Requires: Jinja2, pyyaml, configparser, aiohttp-jinja2, bcrypt, requests, voluptuous, astral, sseclient, feedparser, websocket-client, async, iso8601, daemonize, aiohttp
Classifiers:
  Development Status :: 5 - Production/Stable
  Intended Audience :: Developers
  License :: OSI Approved :: Apache Software License
  Natural Language :: English
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5
  Programming Language :: Python :: 3.6
  Topic :: Home Automation
Entry-points:
  [console_scripts]
  appdaemon = appdaemon.admain:main
```
My ```apps.yaml``` config file has this configuration for this app:
```
switch_reset:
  module: switch_reset
  class: SwitchReset
  file: "/home/homeassistant/.homeassistant/switch_states"
  delay: 10
```
And AppDaemon is connecting to a HomeAssistant installation with version 0.54.0.

The error I get when starting the app is:
```
Oct 11 16:47:33 jumphost appdaemon[21082]: 2017-10-11 16:47:33.365816 INFO Loading Module: /home/homeassistant/.homeassistant/apps/switch_reset.py
Oct 11 16:47:33 jumphost appdaemon[21082]: 2017-10-11 16:47:33.374733 WARNING ------------------------------------------------------------
Oct 11 16:47:33 jumphost appdaemon[21082]: 2017-10-11 16:47:33.375264 WARNING Unexpected error during loading of switch_reset.py:
Oct 11 16:47:33 jumphost appdaemon[21082]: 2017-10-11 16:47:33.375624 WARNING ------------------------------------------------------------
Oct 11 16:47:33 jumphost appdaemon[21082]: 2017-10-11 16:47:33.377857 WARNING Traceback (most recent call last):
Oct 11 16:47:33 jumphost appdaemon[21082]:   File "/usr/local/lib/python3.5/dist-packages/appdaemon/appdaemon.py", line 900, in read_app
Oct 11 16:47:33 jumphost appdaemon[21082]:     conf.modules[module_name] = importlib.import_module(module_name)
Oct 11 16:47:33 jumphost appdaemon[21082]:   File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
Oct 11 16:47:33 jumphost appdaemon[21082]:     return _bootstrap._gcd_import(name[level:], package, level)
Oct 11 16:47:33 jumphost appdaemon[21082]:   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
Oct 11 16:47:33 jumphost appdaemon[21082]:   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
Oct 11 16:47:33 jumphost appdaemon[21082]:   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
Oct 11 16:47:33 jumphost appdaemon[21082]:   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
Oct 11 16:47:33 jumphost appdaemon[21082]:   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
Oct 11 16:47:33 jumphost appdaemon[21082]:   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
Oct 11 16:47:33 jumphost appdaemon[21082]:   File "/home/homeassistant/.homeassistant/apps/switch_reset.py", line 4, in <module>
Oct 11 16:47:33 jumphost appdaemon[21082]:     import globals
Oct 11 16:47:33 jumphost appdaemon[21082]: ImportError: No module named 'globals'
Oct 11 16:47:33 jumphost appdaemon[21082]: 2017-10-11 16:47:33.378303 WARNING ------------------------------------------------------------

```
Any idea what I'm missing?
Thanks!

**Comment by mad-ady** [comment]
I've commented out the ```import globals``` line and the module was loaded correctly:
```
Oct 11 16:55:32 jumphost appdaemon[21082]: 2017-10-11 16:55:32.009967 INFO Reloading Module: /home/homeassistant/.homeassistant/apps/switch_reset.py
Oct 11 16:55:32 jumphost appdaemon[21082]: 2017-10-11 16:55:32.011464 INFO Loading Module: switch_reset
Oct 11 16:55:32 jumphost appdaemon[21082]: 2017-10-11 16:55:32.024869 INFO Loading Object switch_reset using class SwitchReset from module switch_reset
Oct 11 16:55:32 jumphost appdaemon[21082]: 2017-10-11 16:55:32.068460 INFO Loading Object switch_reset using class SwitchReset from module switch_reset
```
I've tested and it restores the state of input_sliders, but not input_booleans. I will have to look into it. Just want to make sure the ```import globals``` statement is not a key element.

**Comment by acockburn** [comment]
Globals is just a module I use in my setup to store values used in more than one app - if you aren't doing that its fine to leave it out.
