### ISSUE TITLE
Crash on broken symlink

### ISSUE THREAD

**Issue by petersohn** [home-assistant/appdaemon#158]
I am using AppDaemon 2.1.10. If the app directory contains a broken symlink, AppDaemon crashes at startup.

I got the following output on the terminal:

```
Traceback (most recent call last):                                 
  File "/srv/homeassistant/bin/appdaemon", line 11, in <module>    
    sys.exit(main())             
  File "/srv/homeassistant/lib/python3.4/site-packages/appdaemon/admain.py", line 519, in main                                         
    run()                        
  File "/srv/homeassistant/lib/python3.4/site-packages/appdaemon/admain.py", line 50, in run                                           
    ad.run_ad(loop, tasks)       
  File "/srv/homeassistant/lib/python3.4/site-packages/appdaemon/appdaemon.py", line 1363, in run_ad                                   
    read_apps(True)              
  File "/srv/homeassistant/lib/python3.4/site-packages/appdaemon/appdaemon.py", line 1016, in read_apps                                
    modified = os.path.getmtime(file)                              
  File "/usr/lib/python3.4/genericpath.py", line 55, in getmtime   
    return os.stat(filename).st_mtime                              
FileNotFoundError: [Errno 2] No such file or directory: '/home/homeassistant/.homeassistant/appdaemon/apps/foobar.py' 
```

The log file contains the following items:

```
INFO AppDaemon Version 2.1.10 starting                             
INFO Configuration read from: /home/homeassistant/.homeassistant/appdaemon/appdaemon.yaml                                              
INFO Starting Apps               
INFO Got initial state  
```

**Comment by acockburn** [comment]
OIK, I'll add some code to make this a little more robust at some point.

**Comment by acockburn** [comment]
As of 3.0 this will result in an error message when AD is first run.
