### ISSUE TITLE
Accessing self.entites error, get_state() works

### ISSUE THREAD

**Issue by tschmidty69** [home-assistant/appdaemon#177]
Trying to access an entities states and tried to do it the "right" way :-)

entity: self.entities.media_player.mopidy.attributes.source_list

[dates and precess name stripped for readability]
```
2017-12-10 11:19:16.826340 WARNING ------------------------------------------------------------
2017-12-10 11:19:16.826772 WARNING Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 515, in worker
    function(args["event"], data, args["kwargs"])
  File "/home/homeassistant/.homeassistant/apps/jarvis.py", line 120, in jarvis_music
    self.entities.media_player.mopidy.attributes.source_list,
  File "/srv/homeassistant/lib/python3.6/site-packages/appdaemon/appapi.py", line 29, in __get__
    state = utils.StateAttrs(conf.ha_state)                                                                         
  File "/srv/homeassistant/lib/python3.6/site-packages/appdaemon/utils.py", line 89, in __init__
    device, name = entity.split(".")
ValueError: too many values to unpack (expected 2)
2017-12-10 11:19:16.827010 WARNING ------------------------------------------------------------
```

This works properly
```
self.get_state( "media_player.mopidy", "source_list")
```
Guessing maybe because source_list is a list and not a bare atrribute?

**Comment by acockburn** [comment]
get_state has some extra code to check if the required attribute is in the attributes list and figure it out. I am guessing that the other method was never tested on attributes or a bug was introduced at some point. I have been working on that code recently and changed it around a little, I'll make sure this works in 3.0.

**Comment by acockburn** [comment]
The code for this piece has changed in 3.0, and when testing this too try and reproduce it seems to work OK. Closing for now - I'll reopen if you can reproduce this in 3.0 when it is released.
