### ISSUE TITLE
Issues getting working with unraid

### ISSUE THREAD

**Issue by twistedatoms** [home-assistant/appdaemon#193]
From what i can tell the commands are all there and should be working but if you look at the log there is several errors. The dock starts up but i cannot access the dashboards at the appropriate URL.

the instructions I followed where http://appdaemon.readthedocs.io/en/latest/DOCKER_TUTORIAL.html

docker run -d --name="AppDaemon" --net="bridge" -e TZ="America/Anchorage" -e HOST_OS="unRAID" -e "HA_URL"="http://172.17.17.201:8123" -e "HA_KEY"="XXXXX" -e "DASH_URL"="http://$HOSTNAME:5050" -e "EXTRA_CMD"="-D DEBUG" -p 5050:5050/tcp -v "/mnt/user/appdata/AppDaemon/":"/conf":rw acockburn/appdaemon

###### below here is the log file after startup #######

ErrorWarningSystemArrayLogin

2017-12-31 14:17:56.929179 INFO AppDaemon Version 2.1.12 starting

2017-12-31 14:17:56.929385 INFO Configuration read from: /conf/appdaemon.yaml
2017-12-31 14:17:56.929492 DEBUG AppDaemon Section: {'logfile': 'STDOUT', 'errorfile': 'STDERR', 'threads': 10}
2017-12-31 14:17:56.929590 DEBUG Hass Section: {'ha_url': 'http://172.17.17.201:8123', 'ha_key': 'XXXXXX'}
2017-12-31 14:17:56.929684 DEBUG HADashboard Section: {'dash_url': 'http://Hass:5050'}
2017-12-31 14:17:56.929775 DEBUG Calling HA for config with key: XXXXXX and url: http://172.17.17.201:8123
2017-12-31 14:17:56.929863 DEBUG get_ha_config()
2017-12-31 14:17:56.929961 DEBUG get_ha_config: url is http://172.17.17.201:8123/api/config
2017-12-31 14:17:56.938446 DEBUG Success
2017-12-31 14:17:56.938641 DEBUG {'components': ['config', 'map', 'sensor.nest', 'climate.nest', 'light.isy994', 'switch', 'binary_sensor.isy994', 'tts', 'media_player.cast', 'lock', 'logbook', 'script', 'automation', 'cover', 'media_player', 'binary_sensor', 'group', 'discovery', 'isy994', 'climate', 'history', 'config.group', 'binary_sensor.nest', 'http', 'camera.nest', 'sensor.isy994', 'fan', 'fan.isy994', 'config.core', 'sensor.darksky', 'config.customize', 'camera', 'websocket_api', 'media_player.roku', 'cover.isy994', 'zone', 'system_log', 'switch.isy994', 'sensor', 'lock.isy994', 'cloud', 'conversation', 'updater', 'frontend', 'recorder', 'api', 'config.script', 'notify', 'config.automation', 'sun', 'nest', 'light'], 'config_dir': '/config', 'elevation': 98, 'latitude': 61.4065, 'location_name': 'Valdez', 'longitude': -145.667, 'time_zone': 'America/Anchorage', 'unit_system': {'length': 'mi', 'mass': 'lb', 'temperature': '°F', 'volume': 'gal'}, 'version': '0.60.0', 'whitelist_external_dirs': ['/config/www']}

2017-12-31 14:17:56.984442 INFO Starting Apps
2017-12-31 14:17:56.984626 DEBUG Entering run()
2017-12-31 14:17:57.000246 DEBUG Creating worker threads ...
2017-12-31 14:17:57.002051 DEBUG Done
2017-12-31 14:17:57.002203 DEBUG Calling HA for initial state with key: XXXXXX and url: http://172.17.17.201:8123
2017-12-31 14:17:57.002318 DEBUG Refreshing HA state
2017-12-31 14:17:57.002436 DEBUG get_ha_state: url is http://172.17.17.201:8123/api/states
2017-12-31 14:17:57.011310 INFO Got initial state
2017-12-31 14:17:57.011588 DEBUG Reading Apps
2017-12-31 14:17:57.012128 INFO Loading Module: /conf/apps/hello.py
2017-12-31 14:17:57.012913 INFO Loading Object hello_world using class HelloWorld from module hello
2017-12-31 14:17:57.081326 INFO hello_world: Hello from AppDaemon
2017-12-31 14:17:57.082375 INFO hello_world: You are now ready to run Apps!
2017-12-31 14:17:57.082467 INFO App initialization complete
2017-12-31 14:17:57.082571 DEBUG Starting timer loop
2017-12-31 14:17:57.082741 INFO Starting dashboard
2017-12-31 14:17:57.085499 WARNING ------------------------------------------------------------

2017-12-31 14:17:57.085607 WARNING Unexpected error in dashboard thread

2017-12-31 14:17:57.085687 WARNING ------------------------------------------------------------

2017-12-31 14:17:57.086700 WARNING Traceback (most recent call last):

File "/usr/local/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 480, in __init__
raise ValueError('Not a directory')
ValueError: Not a directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/appdaemon/rundash.py", line 319, in run_dash
setup_routes(conf.dashboard_obj)
File "/usr/local/lib/python3.6/site-packages/appdaemon/rundash.py", line 289, in setup_routes
app.router.add_static('/compiled_javascript', dashboard.compiled_javascript_dir)
File "/usr/local/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 924, in add_static
append_version=append_version)
File "/usr/local/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 483, in __init__
"No directory exists at '{}'".format(directory)) from error

ValueError: No directory exists at '/conf/compiled/javascript'

2017-12-31 14:17:57.086800 WARNING ------------------------------------------------------------

2017-12-31 14:17:57.086884 INFO API is disabled
2017-12-31 14:17:57.086976 DEBUG Start Loop
2017-12-31 14:17:57.090447 INFO Connected to Home Assistant 0.60.0
2017-12-31 14:17:58.004639 DEBUG Main loop compute time: 2.0ms
2017-12-31 14:17:59.003681 DEBUG Main loop compute time: 2.0ms
2017-12-31 14:18:00.004372 DEBUG Main loop compute time: 2.0ms

**Comment by trevorpgit** [comment]
I ended up creating the compiled folder manually, and I think I also had to create the compiled/css and compiled/javascript folderd manually as well.

I've since been able to remove the compiled/css and compiled/javascript folders, and they're auto-created so I don't recall if this was strictly necessary to create them.

The error message is actually helpful if you can find the line in it you need.

**ValueError: No directory exists at '/conf/compiled/javascript'**

So in your case (based on your docker command above), you'd need to create /mnt/user/appdata/AppDaemon/compiled, and possibly /mnt/user/appdata/AppDaemon/compiled/css and /mnt/user/appdata/AppDaemon/compiled/javascript.

I'd start with just the compiled folder and work from there checking any error messages.

**Comment by acockburn** [comment]
This has been reported before and I believe it is fixed in the upcoming
AppDaemon 3.0. In the meantime the workaround is to create the directories
manually.

**Comment by twistedatoms** [comment]
I created the 3 folders suggested above and all worked. I should have investigated a bit further but I have always been hesitant to customize docker images. Thank you for the quick answer and resolution.

**Comment by acockburn** [comment]
No problem - glad you have it working!
