### ISSUE TITLE
AppDaemon picking up files in .AppleDouble Directory

### ISSUE THREAD

**Issue by uchagani** [home-assistant/appdaemon#227]
AppDaemon is picking up files in the ```.AppleDouble``` directory even if ```.AppleDouble``` is listed in ```exclude_dirs```.  This makes it impossible to mount a directory on a mac and edit the files. Unmounting the directory and removing the ```.AppleDouble``` directory fixes the issue.

AppDaemon Version: appdaemon 3.0.0b1

HA Version: 0.61.1

OS: Raspbian GNU/Linux 9 (stretch)

Stacktrace:

```
2018-01-23 19:09:20.474507 WARNING AppDaemon: ------------------------------------------------------------
2018-01-23 19:09:20.475251 INFO AppDaemon: Loading Module: /home/pi/homeassistant/conf/apps/.AppleDouble/hello.py
2018-01-23 19:09:20.476843 WARNING AppDaemon: ------------------------------------------------------------
2018-01-23 19:09:20.477523 WARNING AppDaemon: Unexpected error during loading of hello.py:
2018-01-23 19:09:20.478018 WARNING AppDaemon: ------------------------------------------------------------
2018-01-23 19:09:20.479341 WARNING AppDaemon: Traceback (most recent call last):
  File "/home/pi/homeassistant/lib/python3.5/site-packages/appdaemon/appdaemon.py", line 1460, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/home/pi/homeassistant/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 669, in exec_module
  File "<frozen importlib._bootstrap_external>", line 775, in get_code
  File "<frozen importlib._bootstrap_external>", line 735, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ValueError: source code string cannot contain null bytes
```

Appdaemon.yaml:

```
appdaemon:
  logfile: STDOUT
  errorfile: STDERR
  threads: 10
  api_port: 5000
  exclude_dirs:
    - .AppleDouble
  plugins:
    HASS:
      type: hass
      ha_url: https://xxxx.duckdns.org:8123
      ha_key: <my_password>
      cert_verify: False
```

**Comment by acockburn** [comment]
In 3.0b2, files that are not defined in apps.yaml or otherwise imported will be ignored, so this problem should go away without the need to use the exclude.

I'll take a look at the exclude to see what is happening however.

**Comment by uchagani** [comment]
Do you have an idea of when 3.0b2 will be released?

**Comment by acockburn** [comment]
Maybe a week or two - the fix is in the dev version of you want to give it a try.

**Comment by uchagani** [comment]
Cool I'll try it this evening.

**Comment by uchagani** [comment]
are there instructions on running the dev version?

**Comment by uchagani** [comment]
figured it out.  for anyone else looking in the future

```
git clone https://github.com/home-assistant/appdaemon.git
cd appdaemon
pip3 install .
```

**Comment by uchagani** [comment]
@acockburn v3.0b2 still suffers from the same issue.  Here is the logs and stacktrace:

```
2018-01-24 02:36:50.996317 INFO AppDaemon Version 3.0.0b2 starting
2018-01-24 02:36:50.996975 INFO Configuration read from: /home/pi/homeassistant/conf/appdaemon.yaml
2018-01-24 02:36:50.999199 INFO AppDaemon: Starting Apps
2018-01-24 02:36:51.000676 WARNING AppDaemon: apps.yaml in the Config directory is deprecated. Please move apps.yaml to the apps directory.
2018-01-24 02:36:51.011717 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2018-01-24 02:36:51.235104 INFO AppDaemon: HASS: HASS Plugin Initializing
2018-01-24 02:36:51.235768 INFO AppDaemon: HASS: HASS Plugin initialization complete
2018-01-24 02:36:51.236628 INFO Dashboards are disabled
2018-01-24 02:36:51.237113 INFO Starting API
2018-01-24 02:36:51.307035 INFO AppDaemon: HASS: Connected to Home Assistant 0.61.1
2018-01-24 02:36:51.604250 INFO AppDaemon: Got initial state from namespace default
2018-01-24 02:36:53.530785 INFO AppDaemon: Loading Module: /home/pi/homeassistant/conf/apps/hello.py
2018-01-24 02:36:53.532390 WARNING AppDaemon: ------------------------------------------------------------
2018-01-24 02:36:53.532915 WARNING AppDaemon: Unexpected error during loading of hello.py:
2018-01-24 02:36:53.533386 WARNING AppDaemon: ------------------------------------------------------------
2018-01-24 02:36:53.538151 WARNING AppDaemon: Traceback (most recent call last):
  File "/home/pi/appdaemon/lib/python3.5/site-packages/appdaemon/appdaemon.py", line 1516, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 669, in exec_module
  File "<frozen importlib._bootstrap_external>", line 775, in get_code
  File "<frozen importlib._bootstrap_external>", line 735, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ValueError: source code string cannot contain null bytes
```

**Comment by acockburn** [comment]
Something is off here - that isn't the same file you originally reported, its in apps not apps/.AppleDouble

Do you have an invalid python file called  hello.yaml at the top level with an apps.yaml entry?

**Comment by uchagani** [comment]
ah yes, you are correct.  Should I file a separate issue?  The error message seems to be the same.  

On another note, I saw the deprecation warning about ```apps.yaml``` needing to be in the ```apps``` directory and when I moved it into the ```apps``` directory I get the following encoding error:

```
2018-01-24 02:44:57.289166 INFO AppDaemon Version 3.0.0b2 starting
2018-01-24 02:44:57.289824 INFO Configuration read from: /home/pi/homeassistant/conf/appdaemon.yaml
2018-01-24 02:44:57.292058 INFO AppDaemon: Starting Apps
Traceback (most recent call last):
  File "/home/pi/appdaemon/bin/appdaemon", line 11, in <module>
    load_entry_point('appdaemon==3.0.0b2', 'console_scripts', 'appdaemon')()
  File "/home/pi/appdaemon/lib/python3.5/site-packages/appdaemon/admain.py", line 335, in main
    admain.main()
  File "/home/pi/appdaemon/lib/python3.5/site-packages/appdaemon/admain.py", line 331, in main
    self.run(appdaemon, hadashboard)
  File "/home/pi/appdaemon/lib/python3.5/site-packages/appdaemon/admain.py", line 58, in run
    self.AD = ad.AppDaemon(self.logger, self.error, loop, **appdaemon)
  File "/home/pi/appdaemon/lib/python3.5/site-packages/appdaemon/appdaemon.py", line 221, in __init__
    self.app_config = self.read_config()
  File "/home/pi/appdaemon/lib/python3.5/site-packages/appdaemon/appdaemon.py", line 1351, in read_config
    config = self.read_config_file(os.path.join(root, file))
  File "/home/pi/appdaemon/lib/python3.5/site-packages/appdaemon/appdaemon.py", line 1393, in read_config_file
    config_file_contents = yamlfd.read()
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 33: invalid continuation byte
```

**Comment by acockburn** [comment]
Encoding errors usually mean that the compiled version of the .py file has somehow become corrupted. Try removing any .prc files and see if that helps.

**Comment by uchagani** [comment]
already tried deleting the ```__pycache__``` directory, still the same encoding issue.  Anything else I can try to nail this down?

**Comment by acockburn** [comment]
Looking closer, looks like a problem in your apps.yaml file

**Comment by uchagani** [comment]
apps.yaml:

```
hello_world:
  module: hello
  class: HelloWorld
```


hello.py

```
import appdaemon.plugins.hass.hassapi as hass

class HelloWorld(hass.Hass):

  def initialize(self):
     self.log("Hello from AppDaemon")
     self.log("You are now ready to run Apps!")
```

I took the samples from the latest docs.
