### ISSUE TITLE
HADashboard doesn't get updates from HASS

### ISSUE THREAD

**Issue by dlashua** [home-assistant/appdaemon#239]
appdaemon 3.0.0b1
hass 0.63.1
Python 3.5.3

Sometime in the last few HASS updates (maybe in 0.63.0, but certainly in the current 0.63.1) HADashboard stopped updating values when state changes in HASS. 

To reproduce, I have a switch in a Dashboard. When I toggle that switch in HASS, the switch does not toggle on the Dashboard. Another example is in climate widgets. Changing the set temperature in the Dashboard results in the temperature being changed in HASS, however, that temperature change is never update on the Dashboard. Reloading the Dashboard, of course, refreshes all values to their current states, however, the refresh does not cause new updates to display.

**Comment by acockburn** [comment]
Do you have any errors in your logs? All is fine for me.

**Comment by dlashua** [comment]
I have no idea what the issue was, but it's working now.

I stopped appdaemon and started it on the command line (instead of using the service) to make sure I could see all the logs in order to confirm there was nothing in the logs. And then it started working. Even when I start it again as a service. I'm fairly sure I restarted appdaemon after upgrading hass... but... maybe not?

Sorry for the false alarm. All is well.

**Comment by Robinsir** [comment]
I have same problem.But I don't know how to make it work. 

appdaemon 2.1.12
home assistant 0.64.0
Python 3.6.3

Refreshes the web,all values to their current states,but I pressed button ,It doesn't work.
I pressed button on homeassistant switch, It also don't refreshes states in dashboard.

Log:
``
2018-03-03 10:41:43.854396 INFO hello_world: Hello from AppDaemon
2018-03-03 10:41:43.854802 INFO hello_world: You are now ready to run Apps!
2018-03-03 10:41:43.854857 INFO App initialization complete
2018-03-03 10:41:43.854966 INFO Starting dashboard
2018-03-03 10:41:43.856523 INFO Starting API
2018-03-03 10:41:43.858552 INFO Connected to Home Assistant 0.64.0
2018-03-03 10:41:46.658259 INFO function [get_dashboard] finished in 17 ms
2018-03-03 10:41:46.793351 INFO New dashboard connected: Hello Panel
/usr/local/lib/python3.6/dist-packages/appdaemon/rundash.py:181: RuntimeWarning: coroutine 'BaseRequest.post' was never awaited
  data = yield from request.post()
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_protocol.py", line 381, in start
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_app.py", line 310, in _handle
    resp = await handler(request)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 213, in coro
    res = yield from res
  File "/usr/local/lib/python3.6/dist-packages/appdaemon/rundash.py", line 181, in call_service
    data = yield from request.post()
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator

Can you help me? Thanks.
