### ISSUE TITLE
HADashboard doesn't get updates from HASS

### ISSUE THREAD

**Issue by Robinsir** [home-assistant/appdaemon#251]
Hello ,
I have same problem with 
https://github.com/home-assistant/appdaemon/issues/239
But I don't know how to make it work.

appdaemon 2.1.12
home assistant 0.64.0
Python 3.6.3

Refreshes the web,all values to their current states,but I pressed button ,It doesn't work.
I pressed button on homeassistant switch, It also don't refreshes states in dashboard.

Log:
``
2018-03-03 10:41:43.854396 INFO hello_world: Hello from AppDaemon
2018-03-03 10:41:43.854802 INFO hello_world: You are now ready to run Apps!
2018-03-03 10:41:43.854857 INFO App initialization complete
2018-03-03 10:41:43.854966 INFO Starting dashboard
2018-03-03 10:41:43.856523 INFO Starting API
2018-03-03 10:41:43.858552 INFO Connected to Home Assistant 0.64.0
2018-03-03 10:41:46.658259 INFO function [get_dashboard] finished in 17 ms
2018-03-03 10:41:46.793351 INFO New dashboard connected: Hello Panel
/usr/local/lib/python3.6/dist-packages/appdaemon/rundash.py:181: RuntimeWarning: coroutine 'BaseRequest.post' was never awaited
data = yield from request.post()
Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_protocol.py", line 381, in start
resp = await self._request_handler(request)
File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_app.py", line 310, in _handle
resp = await handler(request)
File "/usr/lib/python3.6/asyncio/coroutines.py", line 213, in coro
res = yield from res
File "/usr/local/lib/python3.6/dist-packages/appdaemon/rundash.py", line 181, in call_service
data = yield from request.post()
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator

Can you help me? Thanks.

**Comment by acockburn** [comment]
There were some issues with python 3.6 that have been fixed in the 3.0 beta - I suggest you upgrade and retest.

**Comment by Robinsir** [comment]
ok，I will try it，Thinks.

**Comment by Robinsir** [comment]
Everything is OK when I reinstall home assistant and appdaemon. Thank you for your reply.

**Comment by flok99** [comment]
I've got the same problem with a freshly installed appdaemon:

```
2018-03-16 23:05:19.677900 INFO New dashboard connected: Main panel
/usr/local/lib/python3.5/dist-packages/appdaemon/rundash.py:181: RuntimeWarning: coroutine 'BaseRequest.post' was never awaited
  data = yield from request.post()
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_protocol.py", line 381, in start
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_app.py", line 310, in _handle
    resp = await handler(request)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 213, in coro
    res = yield from res
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/rundash.py", line 181, in call_service
    data = yield from request.post()
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
/usr/local/lib/python3.5/dist-packages/appdaemon/rundash.py:269: RuntimeWarning: coroutine 'WebSocketResponse.send_str' was never awaited
  ws.send_str(data)

```

**Comment by vMeph** [comment]
I have the latest version 3, and im having same problem, the solution is copy the main file .dash paste give it another name and then everything is ok, but in next section you got do same, this is some bug and its benn going for awhile

**Comment by acockburn** [comment]
What exact version of Python and AppDaemon are you using? This should be fixed in AD 3.0 beta 4 and later.

**Comment by vMeph** [comment]
@acockburn 
Python 3.6.4
AppDaemon 0.3.0

**Comment by acockburn** [comment]
0.3.0 is the version of the hass.io addon, not AppDaemon - the AppDaemon version is shown in the log. Can you post that  along with the error please.

**Comment by vMeph** [comment]
@acockburn new update pop up for appdameon just updated and all seems normal now...
thanks for you atention...

**Comment by acockburn** [comment]
Cool - I suspect you were using a version of AppDaemon older than 3.0 beta4 - that's when the fix went in.
