### ISSUE TITLE
UnicodeEncodeError in utils.log()

### ISSUE THREAD

**Issue by daringer** [home-assistant/appdaemon#271]
see snippet below, if e.g., "unit_of_measurement" for a certain entity contains some unicode character log() fails with the error seen below. Quick-fix is very easy, PR follows ....

```--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\xb0' in position 391: ordinal not in range(128)
Call stack:
  File "/usr/bin/appdaemon", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/appdaemon/admain.py", line 365, in main
    admain.main()
  File "/usr/lib/python3.6/site-packages/appdaemon/admain.py", line 361, in main
    self.run(appdaemon, hadashboard)
  File "/usr/lib/python3.6/site-packages/appdaemon/admain.py", line 80, in run
    loop.run_until_complete(asyncio.gather(*pending))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1431, in _run_once
    handle._run()
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.6/site-packages/appdaemon/plugins/hass/hassplugin.py", line 254, in get_updates
    await self.AD.state_update(self.namespace, result["event"])
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 2243, in state_update
    self.log( "DEBUG", data["data"])
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 2355, in log
    utils.log(self.logger, level, message, name, ts)
  File "/usr/lib/python3.6/site-packages/appdaemon/utils.py", line 161, in log
    logger.log(levels[level], "{} {}{} {}".format(timestamp, level, name, msg))
Message: "2018-03-28 17:12:22.406789 DEBUG AppDaemon: {'entity_id': 'sensor.sensor_6_temperature', 'old_state': {'entity_id': 'sensor.sensor_6_temperature', 'state': '10.4', 'attributes': {'node_id': 50, 'value_index': 1, 'value_instance': 1, 'value_id': '72057594881785874', 'old_entity_id': 'sensor.sensor_6_temperature_50_1', 'new_entity_id': 'sensor.sensor_6_temperature', 'unit_of_measurement': '\xb0C', 'friendly_name': 'Sensor 6 Temperature'}, 'last_changed': '2018-03-28T17:11:21.688130+00:00', 'last_updated': '2018-03-28T17:11:21.688130+00:00'}, 'new_state': {'entity_id': 'sensor.sensor_6_temperature', 'state': '10.4', 'attributes': {'node_id': 50, 'value_index': 1, 'value_instance': 1, 'value_id': '72057594881785874', 'old_entity_id': 'sensor.sensor_6_temperature_50_1', 'new_entity_id': 'sensor.sensor_6_temperature', 'unit_of_measurement': '\xb0C', 'friendly_name': 'Sensor 6 Temperature'}, 'last_changed': '2018-03-28T17:12:22.386636+00:00', 'last_updated': '2018-03-28T17:12:22.386636+00:00'}}"
Arguments: ()
```

**Comment by daringer** [comment]
oops, this was to fast, updated again, now seems to be without consequences...

**Comment by acockburn** [comment]
Thanks - I'll give you a little while to test before I merge the PR ;)

**Comment by daringer** [comment]
updated once more, after some reading it looks like this is the safest approach I can come up with...
Should not have any side-effects, especially as log() may encounter literally anything/-type of data this approach will likely have good chances to handle whatever may be thrown fed to it.

**Comment by daringer** [comment]
wish this would be a real-quickfix, but I suppose now it was done in "the right way".... As I am currently relying on this to go on with my HA activities, I'll keep on monitoring and testing this, don't think we are in a hurry for this...

**Comment by acockburn** [comment]
I am merging the PR, so closing.
