### ISSUE TITLE
Constant disconnects (probably after upgrade to 3.6)

### ISSUE THREAD

**Issue by wsw70** [home-assistant/appdaemon#279]
When trying to run my AppDaemon script, I get the following error:

```
D:\MegaSync\dev-perso\domotiqueNG\hass-appdaemon>appdaemon -c . -D DEBUG
2018-04-05 22:14:38.738477 INFO AppDaemon Version 3.0.0 starting
2018-04-05 22:14:38.738977 INFO Configuration read from: .\appdaemon.yaml
2018-04-05 22:14:38.740629 DEBUG AppDaemon Section: None
2018-04-05 22:14:38.741133 DEBUG HADashboard Section: None
2018-04-05 22:14:38.742633 INFO AppDaemon: Starting Apps
2018-04-05 22:14:38.743133 DEBUG AppDaemon: Creating worker threads ...
2018-04-05 22:14:38.745635 DEBUG AppDaemon: Done
2018-04-05 22:14:38.745635 DEBUG AppDaemon: Entering run()
2018-04-05 22:14:38.746635 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2018-04-05 22:14:38.764648 INFO AppDaemon: HASS: HASS Plugin Initializing
2018-04-05 22:14:38.764648 INFO AppDaemon: HASS: HASS Plugin initialization complete
2018-04-05 22:14:38.766149 DEBUG AppDaemon: Starting utility loop
2018-04-05 22:14:38.767151 INFO Dashboards are disabled
2018-04-05 22:14:38.767649 INFO API is disabled
2018-04-05 22:14:38.768150 DEBUG Start Loop
2018-04-05 22:14:38.774654 DEBUG AppDaemon: Event type:ha_disconnected:
2018-04-05 22:14:38.775154 DEBUG AppDaemon: {}
2018-04-05 22:14:38.776156 WARNING AppDaemon: HASS: Disconnected from Home Assistant, retrying in 5 seconds
2018-04-05 22:14:38.776656 WARNING AppDaemon: HASS: ------------------------------------------------------------
2018-04-05 22:14:38.777156 WARNING AppDaemon: HASS: Unexpected error:
2018-04-05 22:14:38.777656 WARNING AppDaemon: HASS: ------------------------------------------------------------
2018-04-05 22:14:38.780158 WARNING AppDaemon: HASS: Traceback (most recent call last):
  File "c:\users\yop\appdata\local\programs\python\python36\lib\site-packages\appdaemon\plugins\hass\hassplugin.py", line 189, in get_updates
    "{}/api/websocket".format(url), sslopt=sslopt
  File "c:\users\yop\appdata\local\programs\python\python36\lib\site-packages\websocket\_core.py", line 494, in create_connection
    websock.connect(url, **options)
  File "c:\users\yop\appdata\local\programs\python\python36\lib\site-packages\websocket\_core.py", line 217, in connect
    options.pop('socket', None))
  File "c:\users\yop\appdata\local\programs\python\python36\lib\site-packages\websocket\_http.py", line 70, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "c:\users\yop\appdata\local\programs\python\python36\lib\site-packages\websocket\_http.py", line 110, in _open_socket
    sock.setsockopt(*opts)
OSError: [WinError 10042] An unknown, invalid, or unsupported option or level was specified in a getsockopt or setsockopt call

2018-04-05 22:14:38.781159 WARNING AppDaemon: HASS: ------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\yop\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
(...)
```

The setup used to work, I upgraded to Python 3.6 today and it may be the reason for the issue (I am not sure).

The HA url defined in `ha_url` works fine when started from a browser so there is connectivity to HA. I have a hard time to understand the cryptic `OSError` though.

The configuration is basic:

```
appdaemon:
  threads: 10
  plugins:
    HASS:
      type: hass
      ha_url: http://hass.my.site.here
      ha_key: the_key_here
```

**Comment by acockburn** [comment]
This seems to be an issue with WIndows - what version of windows are you runing?

Here is a relevant discussion:

https://github.com/websocket-client/websocket-client/issues/370

**Comment by wsw70** [comment]
@acockburn I am running `10.0.14393` and upgraded my Python install to 3.6.5. 

I will report whether the issue is fixed with this upgrade but I hit https://github.com/home-assistant/appdaemon/issues/297 in the meantime.

**Comment by WazWaz** [comment]
I'm seeing the exact same error running HASSIO and Appdaemon on a Pi, so it's not just Windows.
