### ISSUE TITLE
HA restart error message

### ISSUE THREAD

**Issue by turboc1208** [home-assistant/appdaemon#29]
Prior to the latest release, when HA restarted, there was just a little message saying that HA was unreachable.  Now it's a full trace.
```

raceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/appdaemon/appdaemon.py", line 993, in run
    get_ha_state()
  File "/usr/local/lib/python3.4/dist-packages/appdaemon/appdaemon.py", line 905, in get_ha_state
    states = ha.get_ha_state()
  File "/usr/local/lib/python3.4/dist-packages/appdaemon/homeassistant.py", line 164, in get_ha_state
    r = requests.get(apiurl, headers=headers, verify = conf.certpath)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8123): Max retries exceeded with url: /api/states (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x70470cd0>: Failed to establish a new connection: [Errno 111] Connection refused',))

2017-01-24 17:26:43.881362 WARNING ------------------------------------------------------------
2017-01-24 17:26:48.896779 WARNING Not connected to Home Assistant, retrying in 5 seconds
2017-01-24 17:26:48.897406 WARNING ------------------------------------------------------------
2017-01-24 17:26:48.905124 WARNING Unexpected error:
2017-01-24 17:26:48.906047 WARNING ------------------------------------------------------------
2017-01-24 17:26:48.908834 WARNING Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connection.py", line 138, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/util/connection.py", line 98, in create_connection
    raise err
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 361, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.4/http/client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 924, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 859, in send
    self.connect()
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connection.py", line 163, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connection.py", line 147, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x6f5bbb10>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/util/retry.py", line 363, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8123): Max retries exceeded with url: /api/states (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x6f5bbb10>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/appdaemon/appdaemon.py", line 993, in run
    get_ha_state()
  File "/usr/local/lib/python3.4/dist-packages/appdaemon/appdaemon.py", line 905, in get_ha_state
    states = ha.get_ha_state()
  File "/usr/local/lib/python3.4/dist-packages/appdaemon/homeassistant.py", line 164, in get_ha_state
    r = requests.get(apiurl, headers=headers, verify = conf.certpath)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8123): Max retries exceeded with url: /api/states (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x6f5bbb10>: Failed to establish a new connection: [Errno 111] Connection refused',))

2017-01-24 17:26:48.909529 WARNING ------------------------------------------------------------
2
```

It's just kind of ugly.

**Comment by acockburn** [comment]
This has been improved in the next release - it's a balance between spamming the logs and providing enough info for troubleshooting. In the last release there was an issue that was difficult to diagnose without this additional information. I will look into additional use of the DEBUG flag to give more verbose messages along with simpler messages without it.
