### ISSUE TITLE
rss feeds have no domain: basic appdaemon functions failure (self.noone_home())

### ISSUE THREAD

**Issue by kdjordjev** [home-assistant/appdaemon#293]
I am running AppDeamon3 plugin (v1.0.1) in Hasio 0.67.1.

After i installed **rss feed** i am getting crashes in the  **self.noone_home()** function.
It seems like the rss feed have NO domain associated with it, and the  self.noone_home() function crashes when trying to split the domain and entity.  entity_id.split(".")
I assume there might be other cases like this.

Setup:

AppDaemon:
  logfile: STDOUT
  errorfile: STDERR
  threads: 10

  rss_feeds:
    - feed: http://rss.cnn.com/rss/cnn_topstories.rss
      target: **cnn_news**

`

def noone_home(self**kwargs):
   state = self.get_state(**kwargs)
   for entity_id in state.keys():
       log.log("Entity id is " + entity_id)
       thisdevice, thisentity = entity_id.split(".")
       if thisdevice == "device_tracker":
           if state[entity_id]["state"] == "home":
           return False
   return True

`

`
2018-04-20 10:59:33.363131 INFO Modes: Entity id is **cnn_news** 
2018-04-20 10:59:33.363750 WARNING AppDaemon: ------------------------------------------------------------ 
2018-04-20 10:59:33.364834 WARNING AppDaemon: Unexpected error in worker for App Modes: 
2018-04-20 10:59:33.365964 WARNING AppDaemon: Worker Ags: {'name': 'Modes', 'id': UUID('60b022e8-0b7d-4170-9bfc-190e718163c3'), 'type': 'attr', 'function': <bound method Modes.presence_change of <modes.Modes object at 0x734c6090>>, 'attribute': 'state', 'entity': 'device_tracker.mqttuser_10089c37f7f94ee59f6bd7e206e98fb3', 'new_state': 'School', 'old_state': 'not_home', 'kwargs': {'handle': UUID('38631e72-2969-4856-83e0-f495df2ec7a9')}} 

2018-04-20 10:59:33.366636 WARNING AppDaemon: ------------------------------------------------------------ 
2018-04-20 10:59:33.368455 WARNING AppDaemon: Traceback (most recent call last): File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 590, in worker self.sanitize_state_kwargs(app, args["kwargs"])) File "/config/appdaemon/apps/modes.py", line 121, in presence_change self.noone_home() File "/config/appdaemon/apps/modes.py", line 155, in noone_home **thisdevice, thisentity = entity_id.split(".")** 
ValueError: not enough values to unpack (expected 2, got 1) 2018-04-20 10:59:33.369099 WARNING 
AppDa`

**Comment by acockburn** [comment]
This is now fixed in the dev branch and will be in 3.0.2 - rather than change a whole bunch of code, I now require the rss feed to have a domain name, e.g. `rss.cnn_news`
