### ISSUE TITLE
logger throwing AttributeErrors

### ISSUE THREAD

**Issue by SupahNoob** [home-assistant/appdaemon#31]
A simple call to the logger seems to be throwing errors.

`self.log('Killing tshark...')`

```2017-01-29 23:36:41.115474 WARNING ------------------------------------------------------------
2017-01-29 23:36:41.116127 WARNING Unexpected error during loading of find_lf.py:
2017-01-29 23:36:41.116698 WARNING ------------------------------------------------------------
2017-01-29 23:36:41.117736 WARNING Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/appdaemon/appdaemon.py", line 704, in readApp
    term_file(file)
  File "/usr/local/lib/python3.4/dist-packages/appdaemon/appdaemon.py", line 481, in term_file
    term_object(key)
  File "/usr/local/lib/python3.4/dist-packages/appdaemon/appdaemon.py", line 506, in term_object
    conf.objects[name]["object"].terminate()
  File "/home/homeassistant/.homeassistant/appdaemon/conf/apps/find_lf.py", line 44, in terminate
    self.stop(event_name=None, data=None, kwargs=None)
  File "/home/homeassistant/.homeassistant/appdaemon/conf/apps/find_lf.py", line 161, in stop
    self.log('Killing tshark...')
  File "/usr/local/lib/python3.4/dist-packages/appdaemon/appapi.py", line 57, in log
    msg = self._sub_stack(msg)
  File "/usr/local/lib/python3.4/dist-packages/appdaemon/appapi.py", line 40, in _sub_stack
    msg = msg.replace("__module__", stack[2].filename)
AttributeError: 'tuple' object has no attribute 'filename'

2017-01-29 23:36:41.118262 WARNING ------------------------------------------------------------
```

It looks like something is wrong with `_sub_stack` in `appapi`.

**Comment by acockburn** [comment]
What version of python are you running?

**Comment by acockburn** [comment]
I have removed the function temporarily in 1.5.1
