### ISSUE TITLE
error in terminal, while errorlog is set

### ISSUE THREAD

**Issue by ReneTode** [home-assistant/appdaemon#326]
errors appear in the terminal.
2 types:
1)
```
Fatal read error on socket transport
protocol: <RequestHandler none:none connected>
transport: <_SelectorSocketTransport fd=23 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 724, in _read_ready
    data = self._sock.recv(self.max_size)
OSError: [Errno 113] No route to host
```
2)
```
Fatal read error on socket transport
protocol: <RequestHandler none:none connected>
transport: <_SelectorSocketTransport fd=20 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 724, in _read_ready
    data = self._sock.recv(self.max_size)
OSError: [Errno 110] connection timed out
```

no info what is causing it, but home assistant is suffering from the exact same errors. (issues there are already from last year)
anything that could help to debug this would be important

**Comment by ReneTode** [comment]
after that i split up dashboard and AD i can see the errors are related to dashboard.
and because of the fact that HA has the same errors it probably a connection error with an open dashboard that isnt handled well.

**Comment by acockburn** [comment]
Thanks Rene

**Comment by ReneTode** [comment]
it is somehow connected to dashboard, because i dont get the errors in the AD instance without dashboard, but its also connected to the connection with HA somehow.
HA log this night (no ha gui opened)
```
2018-07-04 04:50:28 ERROR (MainThread) [homeassistant.core] Error doing job: Fatal read error on socket transport
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 724, in _read_ready
    data = self._sock.recv(self.max_size)
OSError: [Errno 113] No route to host
2018-07-04 04:50:51 ERROR (MainThread) [homeassistant.core] Error doing job: Fatal read error on socket transport
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 724, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
2018-07-04 04:50:55 ERROR (MainThread) [homeassistant.core] Error doing job: Fatal read error on socket transport
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 724, in _read_ready
    data = self._sock.recv(self.max_size)
OSError: [Errno 113] No route to host
```
the dashboard log at that time: (this is the normal log set with 'logfile')
```
2018-07-04 04:50:33.073115 WARNING AppDaemon: ------------------------------------------------------------
2018-07-04 04:50:33.073850 WARNING AppDaemon: Unexpected error during state_update()
2018-07-04 04:50:33.074291 WARNING AppDaemon: ------------------------------------------------------------
2018-07-04 04:50:33.077165 WARNING AppDaemon: Traceback (most recent call last):
  File "/mnt/usbdrive/pi/Dashvenv/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 2341, in state_update
    await self.dashboard.ws_update(namespace, data)
  File "/mnt/usbdrive/pi/Dashvenv/lib/python3.6/site-packages/appdaemon/rundash.py", line 407, in ws_update
    await ws.send_str(data)
  File "/mnt/usbdrive/pi/Dashvenv/lib/python3.6/site-packages/aiohttp/http_writer.py", line 125, in drain
    yield from self._protocol._drain_helper()
  File "/usr/lib/python3.6/asyncio/streams.py", line 211, in _drain_helper
    yield from waiter
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 724, in _read_ready
    data = self._sock.recv(self.max_size)
OSError: [Errno 113] No route to host
```
i still also get errors in the terminal that are the same.

**Comment by davle** [comment]
I get the same errors since enabling dashboard, for some reason usually at night and only at specific hours, like 04:00 and 05:00. Did you manage to find out what was causing it for you ReneTode?

/ David

**Comment by ReneTode** [comment]
you can prevent apps from reinitialising by adding the line:
```
plugin: None
```
to the args from apps you dont want to restart.
or like me you could use 2 times AD. 1 configured for apps and the other for dashboard.

Andrew is working on better error handling. i think its related to a "bad" connection to a dashboard.

**Comment by davle** [comment]
Since I am running AD in docker it should be easy to set up two instances, thanks for your help.

**Comment by acockburn** [comment]
Rene - I updated aiohttp to version 3.0 in dave a fe days ago and added some error catching so these errors should now go into the log. Can you let me know if you are still seeing this please?

**Comment by ReneTode** [comment]
ok, i will keep an eye on it in my dev area

**Comment by acockburn** [comment]
I also fixed an asynch bug in the dashboard that may have been causing this in the first place.
