### ISSUE TITLE
Custom Plugin Folder

### ISSUE THREAD

**Issue by Odianosen25** [home-assistant/appdaemon#355]
Hello @acockburn, for some reason I can't seem to use the custom plugin folder.

When I create it, and restart AppD, it does see it.

I then try to use it in my apps, but the system doesn't import it and spits out import error.

I am still forced to load my plugins into the plugins folder, which is a lot of work.

Can you kindly assist with what I should do please?

Regards

**Comment by acockburn** [comment]
Can you let me see a logfile please? Also, code with the import statements.

**Comment by Odianosen25** [comment]
Well as for import statement, I used different ones like `import appdaemon.plugins.mqtt.mqttapi as mqtt` or `import appdaemon.custom_plugins.mqtt.mqttapi as mqtt`. Not sure what to use to be honest.

I will have to get the logs later, as I am not home presently. So that will be later in the day.

regards

**Comment by Odianosen25** [comment]
Hello @acockburn ,

This is the error I get when I use `import appdaemon.plugins.mqtt.mqttapi as mqtt`:

```
2018-08-15 20:24:45.570123 WARNING AppDaemon: ------------------------------------------------------------
2018-08-15 20:24:45.571274 WARNING AppDaemon: Unexpected error loading module: /home/pi/.appdaemon/conf/apps/mqtt_test.py:
2018-08-15 20:24:45.572263 WARNING AppDaemon: ------------------------------------------------------------
2018-08-15 20:24:45.584406 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/appdaemon.py", line 2020, in check_app_updates
    self.read_app(mod["name"], mod["reload"])
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/appdaemon.py", line 1803, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/pi/.appdaemon/conf/apps/mqtt_test.py", line 1, in <module>
    import appdaemon.plugins.mqtt.mqttapi as mqtt
ImportError: No module named 'appdaemon.plugins.mqtt.mqttapi'
```

In the logs it initialises as noticed here

```
2018-08-15 20:24:41.927892 INFO AppDaemon Version 3.0.1 starting
2018-08-15 20:24:41.929228 INFO Configuration read from: /home/pi/.appdaemon/conf/appdaemon.yaml
2018-08-15 20:24:41.935817 WARNING config_file: /home/pi/.appdaemon/conf/appdaemon.yaml is owned by pi but appdaemon is running as root
2018-08-15 20:24:41.939902 INFO AppDaemon: Starting Apps
2018-08-15 20:24:41.944214 WARNING config_dir: /home/pi/.appdaemon/conf is owned by pi but appdaemon is running as root
2018-08-15 20:24:41.948832 WARNING appdir: /home/pi/.appdaemon/conf/apps is owned by pi but appdaemon is running as root
2018-08-15 20:24:41.963472 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2018-08-15 20:24:42.043051 INFO AppDaemon: HASS: HASS Plugin Initializing
2018-08-15 20:24:42.045309 INFO AppDaemon: HASS: HASS Plugin initialization complete
2018-08-15 20:24:42.046806 INFO AppDaemon: Loading Custom Plugin MQTT using class MqttPlugin from module mqttplugin
2018-08-15 20:24:42.089799 INFO AppDaemon: MQTT: MQTT Plugin Initializing
2018-08-15 20:24:42.093902 INFO Dashboards are disabled
2018-08-15 20:24:42.094913 INFO Starting API
2018-08-15 20:24:42.133653 INFO AppDaemon: HASS: Connected to Home Assistant 0.73.2
2018-08-15 20:24:42.150442 INFO AppDaemon: MQTT: Connected to Broker at URL 192.168.0.30:1883
2018-08-15 20:24:42.157306 INFO AppDaemon: Got initial state from namespace mqtt
2018-08-15 20:24:42.158441 INFO AppDaemon: MQTT: MQTT Plugin initialization complete
2018-08-15 20:24:42.368969 INFO AppDaemon: Got initial state from namespace hass
```

**Comment by acockburn** [comment]
For custom plugins you should use just the name of the plugin in the import statement, e.g.:

```
import mqttapi as mqtt
``
