### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by Odianosen25** [home-assistant/appdaemon#359]
Hello @acockburn, @ReneTode 

Sometimes I get this error in my `error.log`

```
2018-08-22 18:47:14.783495 WARNING AppDaemon: ------------------------------------------------------------
2018-08-22 18:50:07.735064 WARNING AppDaemon: ------------------------------------------------------------
2018-08-22 18:50:07.737459 WARNING AppDaemon: Unexpected error in worker for App settings:
2018-08-22 18:50:07.738424 WARNING AppDaemon: Worker Ags: {'type': 'event', 'data': {'topic': 'zigbee2mqtt/Living Room Window', 'payload': '{"battery":"100.00","voltage":3005,"linkquality":105,"contact":false}'}, 'function': <bound method Settings.zigbeemqtt_entity of <settings.Settings object at 0x76a5f970>>, 'kwargs': {}, 'id': UUID('97079181-160e-4200-8f0d-1bfc6ea916af'), 'name': 'settings', 'event': 'MQTT'}
2018-08-22 18:50:07.738937 WARNING AppDaemon: ------------------------------------------------------------
2018-08-22 18:50:07.793024 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/appdaemon.py", line 595, in worker
    funcref(args["event"], data, args["kwargs"])
  File "/home/pi/.appdaemon/conf/apps/settings/settings.py", line 73, in zigbeemqtt_entity
    self.set_app_state(entity_id, state = state, attributes = attribute)
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/plugins/mqtt/mqttapi.py", line 95, in set_app_state
    if entity_id in self.get_state(namespace = namespace):
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/plugins/mqtt/mqttapi.py", line 83, in get_state
    return super(Mqtt, self).get_state(namespace, entity, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/appapi.py", line 214, in get_state
    return self.AD.get_state(namespace, device, entity, attribute)
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/appdaemon.py", line 696, in get_state
    return deepcopy(self.state[namespace])
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
```

And it is followed by a constant stream of the error

```
File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
```

Like constantly until all my e`rror.log`s files are filled up that is error.log.1,2,3 are all produced. Then for reasons I know not, it stops. My system still runs as normal, as if nothing had happened. This is like the 4th time I have seen it ever, and I still don't know how to figure out what's leading to it.

It is possible there is something wrong with my plugin, but I can't honestly remember if I have come across the error when working with the Hass plugin.

You can see more of the error logs here
https://www.dropbox.com/sh/r1rgcjm1739uzrr/AACX_7AYrOdUP8wOhviioNcaa?dl=0

Thanks and regards

**Comment by acockburn** [comment]
This line:

`self.set_app_state(entity_id, state = state, attributes = attribute)`

In your App I think is somehow conflicitng with internal variables. Try changing the names of state and attribute to something else and see if the problem persists.

**Comment by Odianosen25** [comment]
Thanks sir,

But that is the issue, I can't seem to replicate it as I have it like that in different apps. It works so good for so long, then all of a sudden I get this errors. Will do as said and try studying it a bit more and see what happens. 

Kind regards

**Comment by acockburn** [comment]
My guess is that every time that line of code runs, it adds a layer of data structure in, and eventually gets to a point where the structure is too deep and you get the recursion error after a large number of calls.

**Comment by Odianosen25** [comment]
Oh ok thanks. Something new I just learnt. That explains why I will have to restart appdaemon before it is cleared.

Thanks

**Comment by acockburn** [comment]
I have a list item to make those reserved names a lot harder to pick by accident :)

**Comment by Odianosen25** [comment]
I finally found the error in my code causing this, it has been rectified and it hasn't occurred.

Closing this.
