### ISSUE TITLE
dictionary update sequence ValueError in appapi

### ISSUE THREAD

**Issue by SupahNoob** [home-assistant/appdaemon#37]
In writing a new app, I came across this bug.

Here is my relevant code:

```
data = {"XX:XX:XX:XX:XX:XX": {"last_seen": "2017-02-04 01:19:19.429865", "location": "Out", "friendly_name": "SupahNoob"}}

...

        # expose this information to the front end, including the full object
        self.set_state('binary_sensor.{}_presence'.format(data['XX:XX:XX:XX:XX:XX']['friendly_name'].lower()),
                       state=data['XX:XX:XX:XX:XX:XX']['location'],
                       attributes=json.dumps(data))
```

raises a ValueError in appapi.py

```
2017-02-03 23:56:53.782014 WARNING ------------------------------------------------------------
2017-02-03 23:56:53.782606 WARNING Unexpected error in worker for App presence_listener:
2017-02-03 23:56:53.782986 WARNING Worker Ags: {'function': <bound method PresenceListener.person_is_home of <presence_listener.PresenceListener object at 0x6feb5350>>, 'data': {'mac': 'XX:XX:XX:XX:XX:XX', 'last_seen': '2017-02-03 23:56:53.758789'}, 'type': 'event', 'name': 'presence_listener', 'event': 'internal_trigger_ishome', 'id': UUID('2102ce75-bc1b-4da2-8737-052c2ababd50'), 'kwargs': {}}
2017-02-03 23:56:53.783268 WARNING ------------------------------------------------------------
2017-02-03 23:56:53.784675 WARNING Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/appdaemon/appdaemon.py", line 458, in worker
    function(args["event"], data, args["kwargs"])
  File "/home/homeassistant/.homeassistant/appdaemon/conf/apps/presence_listener.py", line 81, in person_is_home
    attributes=json.dumps({mac: self.users[mac]}))
  File "/usr/local/lib/python3.4/dist-packages/appdaemon/appapi.py", line 185, in set_state
    args["attributes"].update(kwargs["attributes"])
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

I'm not positive how to fix this one in appapi. I'm passing a full, serialized dictionary to the api, essentially so that the user can have all the information in the front end.

- SN

**Comment by acockburn** [comment]
Hi there - this is failing when trying to set the attributes piece - it's not clear from your code what is actually in there - can you explain a little further?

**Comment by SupahNoob** [comment]
Sure, I changed the code a bit, but it's not much of a matter.

```
2017-02-04 11:15:05.752874 WARNING ------------------------------------------------------------
2017-02-04 11:15:05.753426 WARNING Unexpected error in worker for App presence_listener:
2017-02-04 11:15:05.754236 WARNING Worker Ags: {'type': 'event', 'kwargs': {}, 'event': 'internal_trigger_ishome', 'function': <bound method PresenceListener.person_is_home of <presence_listener.PresenceListener object at 0x708a9250>>, 'id': UUID('5feaadfb-ade3-4790-875c-8404c08d19ae'), 'data': {'mac': 'a1:11:1a:a1:11:1a', 'last_seen': '2017-02-04 11:15:05'}, 'name': 'presence_listener'}
2017-02-04 11:15:05.754639 WARNING ------------------------------------------------------------
2017-02-04 11:15:05.758652 WARNING Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/appdaemon/appdaemon.py", line 458, in worker
    function(args["event"], data, args["kwargs"])
  File "/home/homeassistant/.homeassistant/appdaemon/conf/apps/presence_listener.py", line 91, in person_is_home
    attributes=json.dumps(attributes))
  File "/usr/local/lib/python3.4/dist-packages/appdaemon/appapi.py", line 185, in set_state
    args["attributes"].update(kwargs["attributes"])
ValueError: dictionary update sequence element #0 has length 1; 2 is required

2017-02-04 11:15:05.759490 WARNING ------------------------------------------------------------
```

And the relevant bit of code is below. 
`user_name` is type `str`
`last_seen` is type `str` in the format `%Y-%m-%d %H:%M:%S`
`mac` is type `str` .. I've altered it above in the error, but the format is there for you to understand.

```
        # build the attributes for set_state()
        attributes = {
            "user_name": self.users[mac]['friendly_name'],
            "mac": mac,
            "last_seen": last_seen,
            "friendly_name": "Presence",
            "icon": "mdi:home"
        }

        # expose this information to the front end, including the full object
        self.set_state('binary_sensor.{}_presence'.format(self.users[mac]['friendly_name'].lower()),
                       state=self.users[mac]['location'],
                       attributes=json.dumps(attributes))
```

Let me know if you have more questions
- SN

**Comment by acockburn** [comment]
I think the issue is you are converting the attributes into JSON - that is not required and is in fact positively harmful. Under the covers in AppDaemon, the attributes dictionary is merged with the state dictionary, then the whole thing is converted to JSON ahead of sending it to HA, so you don't need to worry about JSON at all, just Python constructs.

Can you try it without the JSON conversion and report back?

**Comment by SupahNoob** [comment]
Something something over optimization .... I should trust you more. That solved it!

**Comment by acockburn** [comment]
Hehe, glad you got it working :)_
