### ISSUE TITLE
global vars in appdaemon.yaml not working.

### ISSUE THREAD

**Issue by ReneTode** [home-assistant/appdaemon#370]
appdaemon.yaml:
```
appdaemon:
  app_dir: /mnt/usbdrive/pi/appdaemon/ADdev/apps/
  disable_apps: 0
  max_utility_skew: 1
  log_thread_actions: 0
  threads: 80
  plugins:
    HASS:
      type: hass
      ha_key: redacted
      ha_url: http://redacted:8123
      timeout: 60
    MQTT:
      type: mqtt
      verbose: True
      mqtt_client_host: 'redacted'
      mqtt_client_port: redacted

log:
  accessfile: /mnt/usbdrive/pi/HAlogs/ADdev_dashboard.log
  errorfile: /mnt/usbdrive/pi/HAlogs/ADdev_error.log
  logfile: /mnt/usbdrive/pi/HAlogs/ADdev_normal.log
  diagfile:  /mnt/usbdrive/pi/HAlogs/ADdev_diag.log
  log_generations: 5
  log_size: 1000000

global_var:
  directories:
    soundfiles: /mnt/usbdrive/pi/speechfiles/    
  files:
    actionslog: /mnt/usbdrive/pi/HAlogs/verlichtingslog.csv
    soundlogfile: /mnt/usbdrive/pi/HAlogs/soundactions.log
```

function:
```
        self.log(self.config["global_var"])
```

error:
```
2018-09-25 23:35:38.730522 WARNING AppDaemon: ------------------------------------------------------------
2018-09-25 23:35:38.730745 WARNING AppDaemon: Unexpected error running initialize() for test
2018-09-25 23:35:38.730934 WARNING AppDaemon: ------------------------------------------------------------
2018-09-25 23:35:38.733387 WARNING AppDaemon: Traceback (most recent call last):
  File "/mnt/usbdrive/pi/ADvenvdev/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 1575, in init_object
    init()
  File "/mnt/usbdrive/pi/appdaemon/ADdev/apps/testapps/test.py", line 51, in initialize
    self.log(self.config["global_var"])
KeyError: 'global_var'

2018-09-25 23:35:38.733793 WARNING AppDaemon: ------------------------------------------------------------
```

**Comment by acockburn** [comment]
CLosing
