### ISSUE TITLE
running with pm2

### ISSUE THREAD

**Issue by platini76** [home-assistant/appdaemon#420]
/usr/local/bin/appdaemon:3
# -*- coding: utf-8 -*-
^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function._load (/home/pi/.nvm/versions/node/v10.0.0/lib/node_modules/pm2/node_modules/@pm2/io/build/main/src/metrics/transaction.js:110:33)
    at Object.<anonymous> (/home/pi/.nvm/versions/node/v10.0.0/lib/node_modules/pm2/lib/ProcessContainerFork.js:48:21)
/usr/local/bin/appdaemon:3
# -*- coding: utf-8 -*-

**Comment by acockburn** [comment]
What exactly are you trying to do here? It looks like you are trying to run AppDaemon using node ...

That is no kind of AD error, I have no config info or log output so I'm not sure how I can help you.

**Comment by platini76** [comment]
I'm really sorry, I am a noob... and I thank you very much if you can help me.
please ask me which data you need for help me.
I am trying to move my appdaemon.service to pm2

**Comment by acockburn** [comment]
What is pm2?

**Comment by acockburn** [comment]
I think this kind of question is better asked on the forum until we definitely know there is an issue.

**Comment by acockburn** [comment]
So PM 2 seems to be a utility for managing Node processes? AppDaemon has nothing whatsoever to do with Node, it is a Python coded package. Clsoing this for now - please ask on the forum if you need further help.

**Comment by platini76** [comment]
which forum?

**Comment by acockburn** [comment]
https://community.home-assistant.io/

**Comment by platini76** [comment]
ok thanks but there noone reply
