### ISSUE TITLE
Error generated when multiple state changes after listen_event trigger

### ISSUE THREAD

**Issue by gpbenton** [home-assistant/appdaemon#43]
`
        self.listen_state(self.everyone_left, "group.all_devices",
                constrain_start_time = "sunset - 00:05:00",
                constrain_end_time = "23:30:00",
                new = "not_home", duration = 600)
`
With the above event triggered, if the state changes from not_home to home within the duration, I get the following error in the error log and the expiry of the duration.  Nothing bad happens, just a log message at seeming random time.

Edit:
I ought to point out that the time was outside the contraint times.

`
2017-02-16 12:04:40.007071 WARNING ------------------------------------------------------------
2017-02-16 12:04:40.016404 WARNING Unexpected error during exec_schedule() for App: security_lights
2017-02-16 12:04:40.017650 WARNING Args: {'repeat': False, 'kwargs': {'old_state': 'not_home', 'handle': UUID('9fcb6a6f-966c-4ea7-b3a1-cd41c22b115a'), 'duration': 600, 'new_state': 'home', 'attribute': 'state', 'constrain_end_time': '23:30:00', 'constrain_start_time': 'sunset - 00:05:00', 'new': 'home', 'entity': 'group.all_devices'}, 'name': 'security_lights', 'id': UUID('6cbb2e68-7ec8-4914-a712-684ae4d5e8e9'), 'basetime': 1487246680, 'offset': 0, 'interval': 0, 'callback': <bound method SecurityLights.someone_home of <security_lights.SecurityLights object at 0x7f3cd0390240>>, 'type': None, 'timestamp': 1487246680}
2017-02-16 12:04:40.018044 WARNING ------------------------------------------------------------
2017-02-16 12:04:40.020499 WARNING Traceback (most recent call last):
  File "/home/graham/lib/python3.5/site-packages/appdaemon/appdaemon.py", line 395, in exec_schedule
    "kwargs": args["kwargs"],
  File "/home/graham/lib/python3.5/site-packages/appdaemon/appdaemon.py", line 331, in dispatch_worker
    for arg in config[name].keys():
  File "/usr/lib/python3.5/configparser.py", line 956, in __getitem__
    raise KeyError(key)
KeyError: 'security_lights'

2017-02-16 12:04:40.020948 WARNING ------------------------------------------------------------
2017-02-16 12:04:40.021720 WARNING Scheduler entry has been deleted
2017-02-16 12:04:40.022591 WARNING ------------------------------------------------------------

`

**Comment by acockburn** [comment]
Can you post your entire App please?

**Comment by gpbenton** [comment]
I have edited it since the error occurred, but I think the essentials are still there.

`
import appdaemon.appapi as appapi
import datetime

#
# App to turn on lights when nobody at home
#
# Args:
#    lights: A comma separated list of lights

class SecurityLights(appapi.AppDaemon):

    def initialize(self):
        self.log("initalize", level="DEBUG")
        try:
            self.args["lights"]
        except KeyError as e:
            self.log("Argument not found : {}".format(e), level="ERROR")
            return

        # Security Lights are turned off by motion_lights when
        # someone arrives home and there is no motion

        self.listen_state(self.everyone_left, "group.all_devices",
                constrain_start_time = "sunset - 00:05:00",
                constrain_end_time = "23:30:00",
                new = "not_home", duration = 600)
        self.run_at_sunset(self.sunset,
                    offset = datetime.timedelta(minutes = -5).total_seconds())

    def everyone_left(self, entity, attribute, old, new, kwargs):
        for light in self.split_device_list(self.args["lights"]):
            self.turn_on(light)

    def sunset(self, kwargs):
        # Turn on security lights at sunset
        for light in self.split_device_list(self.args["lights"]):
            self.turn_on(light)

    def log(self,message,level="INFO"):
        levels = {
                "CRITICAL": 50,
                "ERROR": 40,
                "WARNING": 30,
                "INFO": 20,
                "DEBUG": 10,
                "NOTSET": 0
                }
        try:
            if levels[level]>=levels[self.args["LOGLEVEL"]]:
                super().log("{} - {}".format(level,message))
        except KeyError:
            super().log("{}".format(message),level)
`

**Comment by acockburn** [comment]
Thanks - this is a weird one. Is it possible that you renamed your app or recompiled it during this period?

It looks like the callback is trying to run at the end of the period but can;t find info on the app,

**Comment by gpbenton** [comment]
I'm pretty sure I didn't do anything like that.  It actually occurred twice - the second time I was waiting to reproduce it.

To reproduce it I set the state of my device_tracker to 'not_home' using the developer tools, which triggered the event.  The state was fairly quickly reset to 'home' by my presence detection, which was not what I was inteding, and while I was figuring out how to stop that, the message cropped up.

The other thing which I think might be important is that I did it outside of the time constraints, so the callback should have been started at all.

**Comment by gpbenton** [comment]
I tried this again today, and I couldn't reproduce it.  The only thing I can think that might have been different is that the app was new yesterday, and appdaemon might not have been reloaded after it had been created.
But for now I'll close the issue and if I see it again I'll add something.
