### ISSUE TITLE
Cant connect to hass: _request() got an unexpected keyword argument 'verify_ssl'

### ISSUE THREAD

**Issue by r0bc94** [home-assistant/appdaemon#450]
When trying to start appdaemon it fails to establish a connection with the running hass instance when using a minimal config which looks kinda like so: 

```
appdaemon:
  threads: 2
  plugins:
    HASS:
      type: hass
      ha_url: http://127.0.0.1:8123
      token: <Access Token>

```

 This is the detailed Log output which I get: 

```
pi@raspberrypi:~/appdaemon $ appdaemon -c `pwd` -D DEBUG
2018-12-16 22:21:55.791194 INFO AppDaemon Version 3.0.2 starting
2018-12-16 22:21:55.792309 INFO Configuration read from: /home/pi/appdaemon/appdaemon.yaml
2018-12-16 22:21:55.793165 DEBUG AppDaemon Section: None
2018-12-16 22:21:55.793839 DEBUG HADashboard Section: None
2018-12-16 22:21:55.800924 INFO AppDaemon: Starting Apps
2018-12-16 22:21:55.803853 WARNING config_dir: /home exists, but is not writeable, owner: root
2018-12-16 22:21:55.808719 DEBUG AppDaemon: Creating worker threads ...
2018-12-16 22:21:55.811921 DEBUG AppDaemon: Done
2018-12-16 22:21:55.812925 DEBUG AppDaemon: Entering run()
2018-12-16 22:21:55.815272 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2018-12-16 22:21:56.165633 INFO AppDaemon: HASS: HASS Plugin Initializing
2018-12-16 22:21:56.167362 INFO AppDaemon: HASS: HASS Plugin initialization complete
2018-12-16 22:21:56.168603 DEBUG AppDaemon: Starting utility loop
2018-12-16 22:21:56.169796 INFO Dashboards are disabled
2018-12-16 22:21:56.170626 INFO API is disabled
2018-12-16 22:21:56.171346 DEBUG Start Loop
2018-12-16 22:21:56.198019 INFO AppDaemon: HASS: Connected to Home Assistant 0.84.2
2018-12-16 22:21:56.215593 DEBUG AppDaemon: HASS: get_ha_config()
2018-12-16 22:21:56.217541 DEBUG AppDaemon: HASS: get_ha_config: url is http://127.0.0.1:8123/api/config
2018-12-16 22:21:56.219522 WARNING AppDaemon: HASS: Error getting metadata
2018-12-16 22:21:56.221288 DEBUG AppDaemon: Event type:ha_disconnected:
2018-12-16 22:21:56.222717 DEBUG AppDaemon: {}
2018-12-16 22:21:56.223651 WARNING AppDaemon: HASS: Disconnected from Home Assistant, retrying in 5 seconds
2018-12-16 22:21:56.224429 WARNING AppDaemon: HASS: ------------------------------------------------------------
2018-12-16 22:21:56.225216 WARNING AppDaemon: HASS: Unexpected error:
2018-12-16 22:21:56.225911 WARNING AppDaemon: HASS: ------------------------------------------------------------
2018-12-16 22:21:56.231170 WARNING AppDaemon: HASS: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/plugins/hass/hassplugin.py", line 203, in get_updates
    self.metadata = await self.get_hass_config()
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/plugins/hass/hassplugin.py", line 315, in get_hass_config
    r = await self.session.get(apiurl, headers=headers, verify_ssl=self.cert_verify)
  File "/home/pi/.local/lib/python3.5/site-packages/aiohttp/client.py", line 403, in get
    **kwargs))
TypeError: _request() got an unexpected keyword argument 'verify_ssl'

2018-12-16 22:21:56.232198 WARNING AppDaemon: HASS: ------------------------------------------------------------
```

Im sure that I missed something and would appreciate any help.

**Comment by acockburn** [comment]
How did you do the install? PIP? What version of `aiohttp` are you running? (`pip show aiohttp`)

**Comment by r0bc94** [comment]
> How did you do the install? PIP?

Yes, I installed appdaemon with pip

> What version of aiohttp are you running?

`1.0.5`

**Comment by ReneTode** [comment]
can you connect to ha with the url:
http://127.0.0.1:8123
in a browser?
or do you have ssl setup in HA?

**Comment by r0bc94** [comment]
Sorry, that it took so long.

> can you connect to ha with the url: http://127.0.0.1:8123 in a browser?

Yes, I can access the homeassistant web interface without any problems.

> or do you have ssl setup in HA?

No, I basically use HA's default config.

**Comment by ReneTode** [comment]
can you post the actual appdaemon.yaml (not kinda like) that you use?

and do you really use THAT url in a browser?

**Comment by acockburn** [comment]
I think the issue is that you are running the wrong version of aiohttp - AppDaemon 3.0.2 requires version aiohttp==2.3.10.

This should have been installed automatically by PIP, I don;t know why it wasnt but if you upgrade it manually to that version it should fix the issue.

**Comment by r0bc94** [comment]
> can you post the actual appdaemon.yaml (not kinda like) that you use?

Its actually the one which I posted above (without the token obviously). 

> I think the issue is that you are running the wrong version of aiohttp - AppDaemon 3.0.2 requires version aiohttp==2.3.10.

Oh, okay. That might be the issue. I will check this as soon as I can.

**Comment by acockburn** [comment]
Any update?

**Comment by r0bc94** [comment]
Sorry, the christmas days where a bit stressfull for me. 

Updating the `aiohttp` Version works for me. Thanks for your help.
