### ISSUE TITLE
Scheduler Errors 

### ISSUE THREAD

**Issue by Odianosen25** [home-assistant/appdaemon#452]
AD version 4.0b1

I got the following errors when a scheduler was being executed. Not sure what led to it.

```
2018-12-18 14:20:42.816046 WARNING AppDaemon: ------------------------------------------------------------
2018-12-18 14:20:42.820886 WARNING AppDaemon: Unexpected error during thread_async() loop()
2018-12-18 14:20:42.829512 WARNING AppDaemon: args: {'function': <bound method State.add_to_attr of <appdaemon.state.State object at 0x758e07d0>>, 'args': ('_threading', 'admin', 'state_callback.49f08604dee3447b9875c03b1a11946a', 'fired', 1), 'kwargs': {}}
2018-12-18 14:20:42.837408 WARNING AppDaemon: ------------------------------------------------------------
2018-12-18 14:20:42.861581 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/thread_async.py", line 39, in loop
    result = await function(*myargs, **mykwargs)
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/state.py", line 389, in add_to_attr
    state = self.get_state(name, namespace, entity_id, attribute="all")
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/state.py", line 340, in get_state
    return deepcopy(self.state[namespace][entity_id])
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 242, in _deepcopy_dict
    for key, value in x.items():
RuntimeError: dictionary changed size during iteration

2018-12-18 14:20:42.863873 WARNING AppDaemon: ------------------------------------------------------------
```

**Comment by acockburn** [comment]
This *should* be addressed by changes in the async branch which will be pushed to dev in a day or two
