### ISSUE TITLE
Thread Bug

### ISSUE THREAD

**Issue by Odianosen25** [home-assistant/appdaemon#455]
Version 4.0b1

 I got the following errors in my `log.log`, 

```
2018-12-21 08:32:29.294516 WARNING AppDaemon: Queue size is 52, suspect thread starvation
2018-12-21 08:32:29.356315 WARNING AppDaemon: ------------------------------------------------------------
2018-12-21 08:32:29.358959 WARNING AppDaemon: Unexpected error during utility()
2018-12-21 08:32:29.361471 WARNING AppDaemon: ------------------------------------------------------------
2018-12-21 08:32:29.366259 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/utility_loop.py", line 103, in loop
    warning_step, warning_iterations = self.AD.threading.check_q_size(warning_step, warning_iterations)
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/threading.py", line 257, in check_q_size
    self.dump_threads()
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/threading.py", line 180, in dump_threads
    t = self.get_state("_threading", "admin", "thread.{}".format(thread), attributes = all)
TypeError: get_state() got an unexpected keyword argument 'attributes'

2018-12-21 08:32:29.368893 WARNING AppDaemon: ------------------------------------------------------------
```

And I think its related to the following scheduler errors

```
2018-12-21 09:45:21.005298 WARNING travel_intent: ------------------------------------------------------------
2018-12-21 09:45:21.007836 WARNING travel_intent: Unexpected error during exec_schedule() for App: travel_intent
2018-12-21 09:45:21.010712 WARNING travel_intent: Args: {'offset': 0, 'interval': 60, 'id': 'e173beba73294eda8b56e1cc342e0889', 'type': None, 'repeat': True, 'pin_app': False, 'name': 'travel_intent', 'basetime': datetime.datetime(2018, 12, 21, 9, 46, 20, 900000, tzinfo=<UTC>), 'pin_thread': -1, 'kwargs': {'__thread_id': 'thread-4', 'leaving_time': 5, 'interval': 60, 'user': 'Odianosen'}, 'timestamp': datetime.datetime(2018, 12, 21, 9, 46, 20, 900000, tzinfo=<UTC>), 'callback': <bound method Travel.run_user_time_to_leave of <travel_intent.Travel object at 0x67af6cf0>>}
2018-12-21 09:45:21.013063 WARNING travel_intent: ------------------------------------------------------------
2018-12-21 09:45:21.024819 WARNING travel_intent: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/scheduler.py", line 163, in exec_schedule
    await self.AD.state.set_state("_scheduler", "admin", "scheduler_callback.{}".format(entry), execution_time = utils.dt_to_str(args["timestamp"].replace(microsecond=0), self.AD.tz))
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/state.py", line 401, in set_state
    old_state = deepcopy(self.state[namespace][entity_id])
KeyError: 'scheduler_callback.5e0c7fa0cc154ecc8b576e9c9fb26afc'

2018-12-21 09:45:21.027368 WARNING travel_intent: ------------------------------------------------------------
2018-12-21 09:45:21.033781 WARNING travel_intent: Scheduler entry has been deleted
2018-12-21 09:45:21.036030 WARNING travel_intent: ------------------------------------------------------------
```

**Comment by acockburn** [comment]
Fixed in async branch will be in dev in a day or two.
