### ISSUE TITLE
when a python module isnt installed and imported in an app AD crashes

### ISSUE THREAD

**Issue by ReneTode** [home-assistant/appdaemon#456]
import anything 
will crash if anything isnt installed
example error:
```
DEV 2018-12-21 15:38:04.463683 AppDaemon       Unexpected error loading module: /mnt/usbdrive/pi/appdaemon/ADdev/apps/testmysensors/test_mysensors.py:
DEV 2018-12-21 15:38:04.464105 AppDaemon       Removing associated apps:
DEV 2018-12-21 15:38:04.470206 AppDaemon       ------------------------------------------------------------
DEV 2018-12-21 15:38:04.470817 AppDaemon       Unexpected error during run()
DEV 2018-12-21 15:38:04.475838 AppDaemon       ------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/usbdrive/pi/ADvenvdevLatest/lib/python3.6/site-packages/appdaemon/app_management.py", line 635, in check_app_updates
    self.read_app(mod["name"], mod["reload"])
  File "/mnt/usbdrive/pi/ADvenvdevLatest/lib/python3.6/site-packages/appdaemon/app_management.py", line 419, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/usbdrive/pi/appdaemon/ADdev/apps/testmysensors/test_mysensors.py", line 3, in <module>
    import mysensors.mysensors as mysensors
ModuleNotFoundError: No module named 'mysensors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/usbdrive/pi/ADvenvdevLatest/lib/python3.6/site-packages/appdaemon/main.py", line 90, in run
    loop.run_until_complete(asyncio.gather(*pending))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
    return future.result()
  File "/mnt/usbdrive/pi/ADvenvdevLatest/lib/python3.6/site-packages/appdaemon/utility_loop.py", line 59, in loop
    self.AD.app_management.check_app_updates)
  File "/mnt/usbdrive/pi/ADvenvdevLatest/lib/python3.6/site-packages/appdaemon/utils.py", line 223, in run_in_executor
    response = list(completed)[0].result()
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/mnt/usbdrive/pi/ADvenvdevLatest/lib/python3.6/site-packages/appdaemon/app_management.py", line 648, in check_app_updates
    if self.app_config[app]["module"] == module:
TypeError: string indices must be integers
DEV 2018-12-21 15:38:04.476510 AppDaemon       ------------------------------------------------------------
DEV 2018-12-21 15:38:04.476924 AppDaemon       AppDeamon Exited
```

**Comment by acockburn** [comment]
Fixed in the latest dev:

```
2018-12-22 09:52:00.471831 WARNING Error: ------------------------------------------------------------
2018-12-22 09:52:00.472398 WARNING Error: Unexpected error loading module: /export/pegasus/hass/appdaemon_test/apps/log.py:
2018-12-22 09:52:00.472784 WARNING Error: ------------------------------------------------------------
2018-12-22 09:52:00.476334 WARNING Error: Traceback (most recent call last):
  File "/export/pegasus/hass/src/appdaemon/appdaemon/app_management.py", line 633, in check_app_updates
    await utils.run_in_executor(self, self.read_app, mod["name"], mod["reload"])
  File "/export/pegasus/hass/src/appdaemon/appdaemon/utils.py", line 231, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/export/pegasus/hass/src/appdaemon/appdaemon/app_management.py", line 415, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/export/pegasus/hass/appdaemon_test/apps/log.py", line 5, in <module>
    import mysensors
ModuleNotFoundError: No module named 'mysensors'

2018-12-22 09:52:00.476867 WARNING Error: ------------------------------------------------------------
2018-12-22 09:52:00.477265 WARNING  AppDaemon  Removing associated apps:
```
