### ISSUE TITLE
date(time) inside YAML breaks AD

### ISSUE THREAD

**Issue by ReneTode** [home-assistant/appdaemon#480]
in DEV version from AD.
YAML translates dates and times to datetime object, the admin needs json serializable elements, and breaks because of it.
we discussed that you will put in a check and try to translate the datetime objects to json serializable elements.

**Comment by ReneTode** [comment]
with admin disabled AD starts but it shows this error in "normal log"
```
DEV 2019-01-17 01:36:44.345131 AppDaemon       App initialization complete
DEV 2019-01-17 01:36:48.960711 AppDaemon       ------------------------------------------------------------
DEV 2019-01-17 01:36:48.961301 AppDaemon       Unexpected error in get_state()
DEV 2019-01-17 01:36:48.961734 AppDaemon       ------------------------------------------------------------
DEV 2019-01-17 01:36:48.964557 AppDaemon       Traceback (most recent call last):
  File "/mnt/usbdrive/pi/ADvenvdevLatest/lib/python3.6/site-packages/appdaemon/http.py", line 513, in get_state
    return web.json_response({"state": state})
  File "/mnt/usbdrive/pi/ADvenvdevLatest/lib/python3.6/site-packages/aiohttp/web_response.py", line 635, in json_response
    text = dumps(data)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'date' is not JSON serializable

DEV 2019-01-17 01:36:48.965077 AppDaemon       ------------------------------------------------------------
DEV 2019-01-17 01:36:48.965578 AppDaemon       API Call to system: status: 500, Unexpected error in get_state()
```
when i try to use
        self.log(self.get_state("app.average_bedtime_rene"),namespace="admin")
in an initialise i get this error in "error log"
```
2019-01-17 01:37:23.754657 WARNING test: ------------------------------------------------------------
2019-01-17 01:37:23.755264 WARNING test: Unexpected error running initialize() for test
2019-01-17 01:37:23.755681 WARNING test: ------------------------------------------------------------
2019-01-17 01:37:23.760993 WARNING test: Traceback (most recent call last):
  File "/mnt/usbdrive/pi/ADvenvdevLatest/lib/python3.6/site-packages/appdaemon/app_management.py", line 95, in initialize_app
    await utils.run_in_executor(self, init)
  File "/mnt/usbdrive/pi/ADvenvdevLatest/lib/python3.6/site-packages/appdaemon/utils.py", line 230, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/mnt/usbdrive/pi/appdaemon/ADdev/apps/testapps/test.py", line 65, in initialize
    self.log(self.get_state("app.average_bedtime_rene"),namespace="admin")
  File "/mnt/usbdrive/pi/ADvenvdevLatest/lib/python3.6/site-packages/appdaemon/adapi.py", line 86, in log
    self._log(logger, msg, *args, **kwargs)
  File "/mnt/usbdrive/pi/ADvenvdevLatest/lib/python3.6/site-packages/appdaemon/adapi.py", line 77, in _log
    logger.log(self._logging.log_levels[level], msg, *args, **kwargs)
  File "/usr/lib/python3.6/logging/__init__.py", line 1374, in log
    self._log(level, msg, args, **kwargs)
TypeError: _log() got an unexpected keyword argument 'namespace'

2019-01-17 01:37:23.761493 WARNING test: ------------------------------------------------------------
```

**Comment by roflcoopter** [comment]
Getting the same error when trying to refresh the admin interface, which sadly makes it unusable.
Is there any workaround for this atm?

**Comment by ReneTode** [comment]
yes, dont use dates or times in the yaml, but put quotes around them and when needed make a datetime object from it in your code

**Comment by acockburn** [comment]
I've had a look at fixing this and come to the conclusion that it's not worth the effort when you can just quote your time as a string and convert it in the app. Placing non-JSON serializable objects into entities will just break stuff all over appdaemon.

**Comment by ReneTode** [comment]
@acockburn i wouldnt suggest Placing non-JSON serializable objects into entities
i would suggest that in AD the yaml is checked before its added to an entity.
or add to the docs with BIG CAPITALS, datetime in yaml must be in qoutes always or you break AD completely!!
make sure its converted to a string so people wont break AD, and dont know why.

**Comment by acockburn** [comment]
OK, I'll look into at least adding checks and documenting this as a limitation

**Comment by acockburn** [comment]
Fixed - it is now possible to use datetime objects and other entities without breaking the AUI or REST, or other plugins.
