### ISSUE TITLE
looping errors in logging.

### ISSUE THREAD

**Issue by ReneTode** [home-assistant/appdaemon#481]
this app:
```
import appdaemon.plugins.hass.hassapi as hass

class logclass(hass.Hass):

    def initialize(self):
        self.listen_log(self.new_log, log = "main_log")

    def new_log(self, name, ts, level, type, message, kwargs):
        self.log(message, log = "allAD")
```
should just move all incoming from main_log to allAD log.
but instead i start looping errors
in main log this
```
DEV 2019-01-17 02:21:08.377132 AppDaemon       ------------------------------------------------------------
DEV 2019-01-17 02:21:08.377932 AppDaemon       Unexpected error occured in LogSubscriptionHandler.emit()
DEV 2019-01-17 02:21:08.384461 AppDaemon       ------------------------------------------------------------
DEV 2019-01-17 02:21:08.389861 AppDaemon       Traceback (most recent call last):
  File "/mnt/usbdrive/pi/ADvenvdevLatest/lib/python3.6/site-packages/appdaemon/logging.py", line 144, in emit
    "asctime": record.asctime,
AttributeError: 'LogRecord' object has no attribute 'asctime'

DEV 2019-01-17 02:21:08.390631 AppDaemon       ------------------------------------------------------------
DEV 2019-01-17 02:21:08.402926 test            None
DEV 2019-01-17 02:21:08.414322 test            i changed something again and again
DEV 2019-01-17 02:21:08.425602 AppDaemon       Previous message repeated 1 times
DEV 2019-01-17 02:21:08.426616 AppDaemon       Unexpected error occured in LogSubscriptionHandler.emit()
DEV 2019-01-17 02:21:08.427645 AppDaemon       ------------------------------------------------------------
DEV 2019-01-17 02:21:08.433902 AppDaemon       Traceback (most recent call last):
  File "/mnt/usbdrive/pi/ADvenvdevLatest/lib/python3.6/site-packages/appdaemon/logging.py", line 144, in emit
    "asctime": record.asctime,
AttributeError: 'LogRecord' object has no attribute 'asctime'

DEV 2019-01-17 02:21:08.437820 AppDaemon       ------------------------------------------------------------
DEV 2019-01-17 02:21:08.497646 AppDaemon       Previous message repeated 1 times
DEV 2019-01-17 02:21:08.499632 AppDaemon       Unexpected error occured in LogSubscriptionHandler.emit()
DEV 2019-01-17 02:21:08.501423 AppDaemon       ------------------------------------------------------------
DEV 2019-01-17 02:21:08.503539 AppDaemon       Traceback (most recent call last):
  File "/mnt/usbdrive/pi/ADvenvdevLatest/lib/python3.6/site-packages/appdaemon/logging.py", line 144, in emit
    "asctime": record.asctime,
AttributeError: 'LogRecord' object has no attribute 'asctime'
```
and then in allAD something simular.

**Comment by ReneTode** [comment]
i thought i deactivated it, but it seems i didnt.
at some moments i get the error a few times and then it stops and at a later point again.
it could be this part that creates the errors:

```
    def initialize(self):
        self.listen_state(self.incoming_log, "sensor.log_transport")
        return

    def incoming_log(self, entity, attribute, old, new, kwargs):
        self.log(new, log = "allAD")
```

**Comment by acockburn** [comment]
Hi Rene - I can;t reproduce this, have you seen it recently?

In your 2nd example above, what is `sensor.log_transport`?

**Comment by ReneTode** [comment]
just a sensor i used to transport logs from 1 AD to another, so i would get 1 big log for several AD versions.
i have closed that attempt months ago, because it didnt work.

**Comment by acockburn** [comment]
OK, I'll close this for now.
