### ISSUE TITLE
Error when initialising app

### ISSUE THREAD

**Issue by Odianosen25** [home-assistant/appdaemon#495]
Recently when my apps are being initialised, like HA is restarted without AD, I get the following errors

```
2019-01-25 22:53:24.493150 WARNING AppDaemon: ------------------------------------------------------------
2019-01-25 22:53:24.495237 WARNING AppDaemon: Unexpected error during process_event()
2019-01-25 22:53:24.499070 WARNING AppDaemon: ------------------------------------------------------------
2019-01-25 22:53:24.686819 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/events.py", line 145, in process_event
    await self.AD.state.process_state_callbacks(namespace, data)
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/state.py", line 151, in process_state_callbacks
    for name in self.AD.callbacks.callbacks.keys():
RuntimeError: dictionary changed size during iteration

2019-01-25 22:53:24.689729 WARNING AppDaemon: ------------------------------------------------------------
``` 
Regards

**Comment by Odianosen25** [comment]
Added to the above, I also get the following sometimes 

```
2019-01-28 17:30:14.179406 INFO location_app: The Presence System in the Living Room is Offline
2019-01-28 17:30:14.198965 WARNING AppDaemon: ------------------------------------------------------------
2019-01-28 17:30:14.208144 WARNING AppDaemon: Unexpected error during thread_async() loop()
2019-01-28 17:30:14.210692 WARNING AppDaemon: args: {'function': <bound method ADStream.send_update of <appdaemon.stream.ADStream object at 0x75c88d70>>, 'kwargs': {}, 'args': ({'namespace': 'global', 'event_type': '__AD_LOG_EVENT', 'data': {'app_name': 'location_app', 'level': 'INFO', 'type': 'log', 'log_type': 'main_log', 'message': 'The Presence System in the Living Room is Offline', 'formatted_message': '2019-01-28 17:30:14.185415 INFO location_app: The Presence System in the Living Room is Offline', 'asctime': '2019-01-28 17:30:14.185415'}},)}
2019-01-28 17:30:14.212355 WARNING AppDaemon: ------------------------------------------------------------
2019-01-28 17:30:14.215461 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/thread_async.py", line 43, in loop
    self.appq.task_done()
  File "/usr/lib/python3.5/asyncio/queues.py", line 203, in task_done
    raise ValueError('task_done() called too many times')
ValueError: task_done() called too many times

2019-01-28 17:30:14.216879 WARNING AppDaemon: ------------------------------------------------------------
```

**Comment by Odianosen25** [comment]
Suspending this issue for the mean time, as my issue seems solved for now. 

Not sure why to be honest.
