### ISSUE TITLE
Error generated when I made a change to App

### ISSUE THREAD

**Issue by Odianosen25** [home-assistant/appdaemon#503]
I have a scheduler constantly running in an app every 0.1 sec depending on the state of an entity, and all been working so far. 

I simply made a change to the app, and I got the error below in my `error.log`:
```
2019-01-30 06:50:09.414500 WARNING odianosen_iphone_cf_setup: ------------------------------------------------------------
2019-01-30 07:03:39.073167 WARNING odianosen_iphone_cf_setup: ------------------------------------------------------------
2019-01-30 07:03:39.074794 WARNING odianosen_iphone_cf_setup: Unexpected error during exec_schedule() for App: odianosen_iphone_cf_setup
2019-01-30 07:03:39.076713 WARNING odianosen_iphone_cf_setup: Args: {'repeat': True, 'name': 'odianosen_iphone_cf_setup', 'basetime': datetime.datetime(2019, 1, 30, 7, 3, 38, 900000, tzinfo=<UTC>), 'offset': 0, 'kwargs': {'end_point_state': 'CF.odianosen_iphone', 'interval': 0.1}, 'type': None, 'pin_app': True, 'callback': <bound method CFSetup.picture_animation of <cf_setup.CFSetup object at 0x5e1d9d50>>, 'id': '48155384fc94449f963ddb8cc5bf221e', 'timestamp': datetime.datetime(2019, 1, 30, 7, 3, 38, 900000, tzinfo=<UTC>), 'interval': 0.1, 'pin_thread': 1}
2019-01-30 07:03:39.078495 WARNING odianosen_iphone_cf_setup: ------------------------------------------------------------
2019-01-30 07:03:39.083851 WARNING odianosen_iphone_cf_setup: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/scheduler.py", line 114, in exec_schedule
    "kwargs": deepcopy(args["kwargs"]),
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/threading.py", line 537, in dispatch_worker
    constrained = await self.check_constraint(arg, myargs["kwargs"][arg], self.AD.app_management.objects[name]["object"])
KeyError: 'odianosen_iphone_cf_setup'

2019-01-30 07:03:39.085127 WARNING odianosen_iphone_cf_setup: ------------------------------------------------------------
2019-01-30 07:03:39.088082 WARNING odianosen_iphone_cf_setup: Scheduler entry has been deleted
2019-01-30 07:03:39.089578 WARNING odianosen_iphone_cf_setup: ------------------------------------------------------------
```
And I got the below in my `log.log`:
```
2019-01-30 07:03:39.091171 WARNING AppDaemon: ------------------------------------------------------------
2019-01-30 07:03:39.092463 WARNING AppDaemon: Unexpected error in scheduler loop
2019-01-30 07:03:39.093792 WARNING AppDaemon: ------------------------------------------------------------
2019-01-30 07:03:39.096207 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/scheduler.py", line 114, in exec_schedule
    "kwargs": deepcopy(args["kwargs"]),
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/threading.py", line 537, in dispatch_worker
    constrained = await self.check_constraint(arg, myargs["kwargs"][arg], self.AD.app_management.objects[name]["object"])
KeyError: 'odianosen_iphone_cf_setup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/scheduler.py", line 382, in loop
    await self.exec_schedule(name, args, uuid_)
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/scheduler.py", line 149, in exec_schedule
    del self.schedule[name][uuid_]
KeyError: 'odianosen_iphone_cf_setup'

2019-01-30 07:03:39.097661 WARNING AppDaemon: ------------------------------------------------------------
```
Now I have made changes to this app several times, and this is the first time this error has popped up.

Regards

**Comment by acockburn** [comment]
I believe this will be addressed with some added locking in the core.

**Comment by Odianosen25** [comment]
Closing for now, might not need to lock
