### ISSUE TITLE
typo in an app prevented AD from restart.

### ISSUE THREAD

**Issue by ReneTode** [home-assistant/appdaemon#515]
I needed to restart AD (dev) and it wouldnt start at all.
errorlog showed a typo i made a few days back
```
2019-02-11 15:31:27.941854 WARNING Error: ------------------------------------------------------------
2019-02-11 15:31:27.943089 WARNING Error: Unexpected error loading module: /mnt/usbdrive/pi/appdaemon/ADdev/apps/create_entities/components/input_number/input_number_alexa_volume.py:
2019-02-11 15:31:27.944108 WARNING Error: ------------------------------------------------------------
2019-02-11 15:31:27.949776 WARNING Error: Traceback (most recent call last):
  File "/mnt/usbdrive/pi/ADvenvdevLatest/lib/python3.6/site-packages/appdaemon/app_management.py", line 644, in check_app_updates
    await utils.run_in_executor(self, self.read_app, mod["name"], mod["reload"])
  File "/mnt/usbdrive/pi/ADvenvdevLatest/lib/python3.6/site-packages/appdaemon/utils.py", line 230, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/mnt/usbdrive/pi/ADvenvdevLatest/lib/python3.6/site-packages/appdaemon/app_management.py", line 426, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/usbdrive/pi/appdaemon/ADdev/apps/create_entities/components/input_number/input_number_alexa_volume.py", line 44
    cmd = self.args["alexa_media_file"], "-d", entity_settings["attributes"]["device_name"], "-e", "vol:" + str(volume)]
                                                                                                                       ^
SyntaxError: invalid syntax

2019-02-11 15:31:27.950988 WARNING Error: ------------------------------------------------------------
```
after correcting the typo AD started as expected.

**Comment by acockburn** [comment]
I'm unable to reproduce this - do yo uhave more info? What was the error when trying to restart AD?

**Comment by ReneTode** [comment]
create a syntaxerror in an app. save it. then restart AD.

in my case AD didnt startup untill i fixed the syntax error in the app.

**Comment by acockburn** [comment]
I tried exactly that and had no issues. Are you able to reproduce it at will? Is there a specific app that caused the issue?

**Comment by ReneTode** [comment]
i dont know anymore andrew.
the problem was 4 months ago. if you cant reproduce it, then close it.
i only had the situation 1 time, when i didnt notice a syntaxerror before i restarted.
normally i always check immediatly after saving an app.

if i have something simular again, or hear from anyone else something simular ill reopen.

**Comment by acockburn** [comment]
OK :)
