### ISSUE TITLE
ImportError: cannot import name 'RLock' running in PyCharm

### ISSUE THREAD

**Issue by foxy82** [home-assistant/appdaemon#547]
Creating a brand new venv in pycharm and just installing the requirements in the setup.py I get the following error when trying to run main.py. Using master checked out from github earlier today.

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/subprocess.py", line 131, in <module>
    import threading
  File "/home/foxy82/PycharmProjects/appdaemon/appdaemon/threading.py", line 10, in <module>
    import logging
  File "/home/foxy82/PycharmProjects/appdaemon/appdaemon/logging.py", line 2, in <module>
    import pytz
  File "/home/foxy82/PycharmProjects/appdaemon/venv/lib/python3.5/site-packages/pytz/__init__.py", line 19, in <module>
    from pytz.lazy import LazyDict, LazyList, LazySet  # noqa
  File "/home/foxy82/PycharmProjects/appdaemon/venv/lib/python3.5/site-packages/pytz/lazy.py", line 1, in <module>
    from threading import RLock
ImportError: cannot import name 'RLock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/foxy82/PycharmProjects/appdaemon/appdaemon/main.py", line 15, in <module>
    import platform
  File "/usr/lib/python3.5/platform.py", line 117, in <module>
    import sys, os, re, subprocess
  File "/usr/lib/python3.5/subprocess.py", line 133, in <module>
    import dummy_threading as threading
  File "/usr/lib/python3.5/dummy_threading.py", line 45, in <module>
    import threading
  File "/home/foxy82/PycharmProjects/appdaemon/appdaemon/threading.py", line 10, in <module>
    import logging
  File "/home/foxy82/PycharmProjects/appdaemon/appdaemon/logging.py", line 2, in <module>
    import pytz
  File "/home/foxy82/PycharmProjects/appdaemon/venv/lib/python3.5/site-packages/pytz/__init__.py", line 19, in <module>
    from pytz.lazy import LazyDict, LazyList, LazySet  # noqa
  File "/home/foxy82/PycharmProjects/appdaemon/venv/lib/python3.5/site-packages/pytz/lazy.py", line 1, in <module>
    from threading import RLock
ImportError: cannot import name 'RLock'
```

**Comment by Odianosen25** [comment]
This issue should be local to your environment. Pls check that you have the all modules properly installed.

Regards

**Comment by acockburn** [comment]
Closing - we don;t have the resources to support other products :( I would suggest asking on the forum for this kind of issue.
