### ISSUE TITLE
Duplicate pyyaml dependencies listed in setup.py causing error on install

### ISSUE THREAD

**Issue by shbatm** [home-assistant/appdaemon#599]
Duplicate `pyyaml` lines in `setup.py` are causing an error when installing `appdaemon` vial local pip because one is pinned at 5.1 and 5.1.1 has been released:

```shell
Traceback (most recent call last):
  File "/home/skynet/src/appdaemon/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/home/skynet/src/appdaemon/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/skynet/src/appdaemon/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (PyYAML 5.1.1 (/home/skynet/src/appdaemon/venv/lib/python3.6/site-packages), Requirement.parse('pyyaml==5.1'), {'appdaemon'})
```

[Line 18](https://github.com/home-assistant/appdaemon/blob/7d5e5ce851c7fcb8e188d1855066d1d52acf79db/setup.py#L18)
[Line 22](https://github.com/home-assistant/appdaemon/blob/7d5e5ce851c7fcb8e188d1855066d1d52acf79db/setup.py#L22)

**Comment by Odianosen25** [comment]
Hello @shbatm,

Apologies abt this, will have that sorted. 

Regards

**Comment by Odianosen25** [comment]
Fixed now so closing
