### ISSUE TITLE
Invalid Service Name: shell_command

### ISSUE THREAD

**Issue by runningman84** [home-assistant/appdaemon#666]
I get an error if I try to run this code:
```
self.call_service('shell_command.cleanup_old_camera_images')
```

What is wrong here? In the hass gui I can call the shell_command just fine....
```
2019-09-11 20:34:54.274284 INFO cleanup_camera_images: Callback trigger_cleanup_callback from sensor.tmp:state 108.44->110.28
2019-09-11 20:34:54.276321 INFO cleanup_camera_images: Calling service shell_command.cleanup_old_camera_images
2019-09-11 20:34:54.276624 WARNING AppDaemon: ------------------------------------------------------------
2019-09-11 20:34:54.276827 WARNING AppDaemon: Unexpected error in worker for App cleanup_camera_images:
2019-09-11 20:34:54.277098 WARNING AppDaemon: Worker Ags: {'name': 'cleanup_camera_images', 'id': UUID('a5018bb0-a19c-4d01-8804-e509705c3591'), 'type': 'attr', 'function': <bound method Cleanup.trigger_cleanup_callback of <cleanup.Cleanup object at 0x7f46710fc9e8>>, 'attribute': 'state', 'entity': 'sensor.tmp', 'new_state': '110.28', 'old_state': '108.44', 'kwargs': {'handle': UUID('73504606-c867-4599-a3f2-56634bb335a5')}}
2019-09-11 20:34:54.277296 WARNING AppDaemon: ------------------------------------------------------------
2019-09-11 20:34:54.277867 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 595, in worker
    self.sanitize_state_kwargs(app, args["kwargs"]))
  File "/config/appdaemon-config.git/apps/cleanup.py", line 46, in trigger_cleanup_callback
    self.call_service(self._cleanup_service)
  File "/usr/lib/python3.6/site-packages/appdaemon/plugins/hass/hassapi.py", line 22, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/appdaemon/plugins/hass/hassapi.py", line 494, in call_service
    self._check_service(service)
  File "/usr/lib/python3.6/site-packages/appdaemon/plugins/hass/hassapi.py", line 490, in _check_service
    raise ValueError("Invalid Service Name: {}".format(service))
ValueError: Invalid Service Name: shell_command.cleanup_old_camera_images


```

**Comment by ReneTode** [comment]
in appdaemon call_service all dots are replaced by a / 
so it should be
```
self.call_service('shell_command/cleanup_old_camera_images')
```

**Comment by acockburn** [comment]
The name of your service should be "shell_command/cleanup_old_camera_images"

**Comment by acockburn** [comment]
@ReneTode beat me to it ;)
