### ISSUE TITLE
TypeError when using self.now_is_between()

### ISSUE THREAD

**Issue by marchingphoenix** [home-assistant/appdaemon#672]
# Summary
Hey Team. While attempting to use `self.now_is_between()` I am receiving an un-expected Exception. Any insight would be appreciated.

# Environment Details
Component | Version 
--- | --- 
AppDaemon Version | 3.0.5
Install Method | Docker:latest
Python Version | 3.6

# Traceback
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 2346, in state_update
    self.process_state_change(namespace, data)
  File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 2314, in process_state_change
    uuid_
  File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 2248, in check_and_disapatch
    "kwargs": kwargs
  File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 536, in dispatch_worker
    constrained = self.check_constraint(arg, args["kwargs"][arg], self.objects[name]["object"])
  File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 495, in check_constraint
    unconstrained = method(value)
  File "/conf/apps/trigger_fans.py", line 71, in is_fan_on
    or self.now_is_between(self.pres_override_start, self.pres_override_stop)
  File "/usr/local/lib/python3.6/site-packages/appdaemon/appapi.py", line 300, in now_is_between
    return self.AD.now_is_between(start_time_str, end_time_str, name)
  File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 1047, in now_is_between
    start_time = self.parse_time(start_time_str, name)
  File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 1072, in parse_time
    parts = re.search('^(\d+):(\d+):(\d+)', time_str)
  File "/usr/local/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```
# Class Snippet
```python
class TriggerFans(hass.Hass):
    def initialize(self):
        # trimmed
        self.pres_override_start = self.args.get("pres_override_start")
        self.pres_override_stop = self.args.get("pres_override_stop")
    def is_fan_on(self, fan):
        return (
            self.get_state(fan) == "on"
            or self.get_state(self.occupancy) == "on"
            or self.now_is_between(self.pres_override_start, self.pres_override_stop)
        )
```
# App Def Snippet
```yaml
trigger_mbr_fan:
  module: trigger_fans
  class: TriggerFans
# trimmed
  pres_override_start: "23:00:00"
  pres_override_stop: "10:00:00"
```

**Comment by ReneTode** [comment]
so you did hide your problem ;) 
i dont think its cleaner, because it wont return the error ;)
