### ISSUE TITLE
Appdaemon 2.0.0beta4 - YAML without HADashboard does not work

### ISSUE THREAD

**Issue by FREImedia** [home-assistant/appdaemon#68]
I just tried to convert one of my Appdaemon instances to the new version of appdaemon 2.0.0beta4. Therefore I converted my config to YAML. I tried starting it without the dashboard part.

This results in the following error, which prevents Appdaemon from startup:

```
Jun 18 22:36:42 watchpi systemd[1]: Started HA AppDaemon.
Jun 18 22:36:48 watchpi appdaemon[11319]: Traceback (most recent call last):
Jun 18 22:36:48 watchpi appdaemon[11319]: File "/usr/local/bin/appdaemon", line 9, in <module>
Jun 18 22:36:48 watchpi appdaemon[11319]: load_entry_point('appdaemon==2.0.0beta4', 'console_scripts', 'appdaemon')()
Jun 18 22:36:48 watchpi appdaemon[11319]: File "/usr/local/lib/python3.4/dist-packages/appdaemon/appdaemon.py", line 1570, in main
Jun 18 22:36:48 watchpi appdaemon[11319]: conf.dash_url = config['HADashboard'].get("dash_url")
Jun 18 22:36:48 watchpi appdaemon[11319]: KeyError: 'HADashboard'
Jun 18 22:36:48 watchpi systemd[1]: hass-appdaemon.service: main process exited, code=exited, status=1/FAILURE
Jun 18 22:36:48 watchpi systemd[1]: Unit hass-appdaemon.service entered failed state.
```

Adding a valid dashboard configuration to the YAML file solves the issue:
```
HADashboard:
  dash_url: 'http://127.0.0.1:5050'
```

**Comment by acockburn** [comment]
Thanks for this - I'll put in a fix in the next version.

**Comment by acockburn** [comment]
Fixed in next version!
