### ISSUE TITLE
run_in() error (ASYNC PR)

### ISSUE THREAD

**Issue by dlashua** [home-assistant/appdaemon#699]
version: dev + async PR

This is likely a ASYNC PR issue:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/appdaemon/app_management.py", line 142, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/local/lib/python3.7/site-packages/appdaemon/utils.py", line 256, in run_in_executor
    response = future.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/conf/apps/conditionengine/ctest.py", line 26, in initialize
    myname=thing['name'])
  File "/conf/apps/conditionengine/conditions.py", line 172, in listen
    handle = c.listen(self.condition_callback)
  File "/conf/apps/conditionengine/conditions.py", line 79, in listen
    handle = self.app.run_at(self.timer_callback, self.times['start'])
  File "/usr/local/lib/python3.7/site-packages/appdaemon/utils.py", line 173, in inner_sync_wrapper
    f = run_coroutine_threadsafe(self, coro(self, *args, **kwargs))
  File "/usr/local/lib/python3.7/site-packages/appdaemon/utils.py", line 265, in run_coroutine_threadsafe
    result = future.result(self.AD.internal_function_timeout)
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/site-packages/appdaemon/adapi.py", line 2162, in run_at
    when = await self.AD.sched._parse_time(start, self.name)["datetime"]
TypeError: 'coroutine' object is not subscriptable
```

**Comment by dlashua** [comment]
Fixed with https://github.com/home-assistant/appdaemon/pull/645
