### ISSUE TITLE
 'str' object has no attribute 'get' while parsing config

### ISSUE THREAD

**Issue by vrs01** [home-assistant/appdaemon#70]
```
pi@raspberrypi_wozi:~/appdaemon $ appdaemon -D DEBUG -c conf
Traceback (most recent call last):
  File "/usr/local/bin/appdaemon", line 11, in <module>
    load_entry_point('appdaemon==2.0.0b4', 'console_scripts', 'appdaemon')()
  File "/usr/local/lib/python3.4/dist-packages/appdaemon/appdaemon.py", line 1553, in main
    conf.logfile = config['AppDaemon'].get("logfile")
AttributeError: 'str' object has no attribute 'get'
```

What can I do about this? Is this an issue with python versions?

**Comment by vrs01** [comment]
I had some equal signs in the yaml config. Had to replace those by :
