### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'conf/appdaemon.cfg'

### ISSUE THREAD

**Issue by biacz** [home-assistant/appdaemon#73]
i just installed it according to https://github.com/home-assistant/appdaemon/blob/master/README.md and https://github.com/home-assistant/appdaemon/blob/master/DASHBOARD.md

cant run appdaemon -c conf because it throws back: FileNotFoundError: [Errno 2] No such file or directory: 'conf/appdaemon.cfg' - when i rename the appdaemon.yaml into appdaemon.cfg it still fails with following error: 

root@raspberrypi:/opt/appdaemon_dashboard/appdaemon# appdaemon -c conf
Traceback (most recent call last):
  File "/usr/local/bin/appdaemon", line 9, in <module>
    load_entry_point('appdaemon==2.0.0beta3.5', 'console_scripts', 'appdaemon')()
  File "/usr/local/lib/python3.4/dist-packages/appdaemon/appdaemon.py", line 1436, in main
    config.read_file(open(config_file))
  File "/usr/lib/python3.4/configparser.py", line 691, in read_file
    self._read(f, source)
  File "/usr/lib/python3.4/configparser.py", line 1058, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'conf/appdaemon.cfg', line: 1
'AppDaemon:\n'

documentation is still very unclear.
what am i missing?

**Comment by biacz** [comment]
updated appdaemon (pip3 uninstall appdaemon && pip3 install .).
progressing
