### ISSUE TITLE
create_vacation called from appdaemon throws 400 Client Error: Bad Request

### ISSUE THREAD

**Issue by iot49** [home-assistant/appdaemon#810]
**Home Assistant release with the issue:**

Home Assistant 0.101.3

**Last working Home Assistant release (if known):**

**Operating environment (Hass.io/Docker/Windows/etc.):**

Docker on Ubuntu (NUC)

**Integration:**

ecobee / appdaemon

**Description of problem:**

The last line of the code below (call_service ecobee/create_vacation) throws an exception when end_date is specified. The command works as expected without the optional parameter end_date.

```python
import appdaemon.plugins.hass.hassapi as hass
import datetime

class Heat(hass.Hass):

    def initialize(self):
        self.listen_state(self.heat_state, 'input_boolean.heat')

    def heat_state(self, entity, attr, old, new, kwargs):
        self.log(f"heat_state {old} -> {new}")
        if new == 'on':
            # Ecobee run schedule
            self.call_service("ecobee/delete_vacation", entity_id="climate.bear_valley", vacation_name="HA")
        else:
            # Ecobee vacation setback
            end = self.datetime() + datetime.timedelta(days=365)
            end_date = end.strftime("%Y-%m-%d")
            self.call_service("ecobee/create_vacation", entity_id="climate.bear_valley", vacation_name="HA", 
                cool_temp=40, heat_temp=10, 
                end_date=end_date)
```

**Problem-relevant `appdaemon.yaml` entries and (fill out even if it seems unimportant):**
```yaml
secrets: /config/secrets.yaml
log:
  logfile: /config/appdaemon/appdaemon.log
  errorfile: /config/appdaemon/appdaemon.log
appdaemon:
  threads: 10
  app_dir: /config/appdaemon/apps
  plugins:
    HASS:
      type: hass
      ha_url: http://hassio/homeassistant
      token: dee738b6a05922b59f2f0f9ab900c ...
hadashboard:
  dash_url: http://127.0.0.1:5050
  dash_dir: /config/appdaemon/dashboards

```

**Traceback (if applicable):**
```
2019-11-15 17:44:47.138455 WARNING AppDaemon: ------------------------------------------------------------
2019-11-15 17:44:47.139255 WARNING AppDaemon: Unexpected error in worker for App heat:
2019-11-15 17:44:47.139960 WARNING AppDaemon: Worker Ags: {'name': 'heat', 'id': UUID('868eed3b-cd88-47ca-92eb-608e9f2a3a97'), 'type': 'attr', 'function': <bound method Heat.heat_state of <heat.Heat object at 0x7f58366b4518>>, 'attribute': 'state', 'entity': 'input_boolean.heat', 'new_state': 'off', 'old_state': 'on', 'kwargs': {'handle': UUID('69c0d858-e578-40dd-b851-f5f2dfd93bc2')}}
2019-11-15 17:44:47.140468 WARNING AppDaemon: ------------------------------------------------------------
2019-11-15 17:44:47.141842 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/appdaemon/appdaemon.py", line 595, in worker
    self.sanitize_state_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/heat.py", line 28, in heat_state
    cool_temp=40, heat_temp=10, end_date=end_date)
  File "/usr/lib/python3.7/site-packages/appdaemon/plugins/hass/hassapi.py", line 22, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/appdaemon/plugins/hass/hassapi.py", line 522, in call_service
    r.raise_for_status()
  File "/usr/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://hassio/homeassistant/api/services/ecobee/create_vacation
```

**Additional information:**

**Comment by Odianosen25** [comment]
This is not an AD issue, as possibly one if the update doesn’t allow for that service call with that parameter. Can the user kindly via the HA interface, try the service with that parameter and let us know if it works fine?

Regards

**Comment by iot49** [comment]
You are right, problem appears to be with the create_vacation service. I inquire the developer of that one. Sorry for the false alarm.

**Comment by Odianosen25** [comment]
@iot49 its alright, and glad you have sorted it out.

We are always here to help, if further issues arise.

Regards
