### ISSUE TITLE
Socketio communication not working

### ISSUE THREAD

**Issue by rogerbi** [home-assistant/appdaemon#850]
Hello,

I have an issue with socketio - it is not working anymore in current release

Installation on HassIo AppDaemon 4 0.1.1

secrets: /config/secrets.yaml
appdaemon:
  app_dir: /config/appdaemon/apps
  plugins:
    HASS:
      type: hass
  latitude: 10
  longitude: 10
  time_zone: Europe/Berlin
  elevation: 10
http:
  url: http://127.0.0.1:5050
  transport: socketio
admin:
api:
hadashboard:

I update dashboard.js to force polling as my old device does only have an old implementation of websocket v76.

 var iosocket = io.connect(stream, {
                transports: ['polling'], upgrade: false, forceBase64: true
});

May be this change might be good in general for old devices...

I get the following error on server-side...

2020-01-17 18:54:53.359739 INFO AppDaemon: function [get_dashboard] finished in 83 ms
message async handler error
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/engineio/asyncio_server.py", line 419, in _trigger_event
    ret = await self.handlers[event](*args)
  File "/usr/lib/python3.8/site-packages/socketio/asyncio_server.py", line 504, in _handle_eio_message
    await self._handle_connect(sid, pkt.namespace)
  File "/usr/lib/python3.8/site-packages/socketio/asyncio_server.py", line 389, in _handle_connect
    success = await self._trigger_event('connect', namespace, sid,
  File "/usr/lib/python3.8/site-packages/socketio/asyncio_server.py", line 478, in _trigger_event
    return await self.namespace_handlers[namespace].trigger_event(
  File "/usr/lib/python3.8/site-packages/socketio/asyncio_namespace.py", line 37, in trigger_event
    ret = await handler(*args)
  File "/usr/lib/python3.8/site-packages/appdaemon/stream.py", line 25, in on_connect
    await self.ADStream.on_connect()
AttributeError: 'ADStream' object has no attribute 'on_connect'

There are no updates on the Dashboard if any sensor change.

I although have branch 4.0.0b1 running on docker - this is working fine….

**Comment by acockburn** [comment]
Thhis could be related to #841 - can you retest when we release 4.0.1 please?

**Comment by acockburn** [comment]
Have you been able to test this in 4.0.1?

**Comment by rogerbi** [comment]
I am quite confused About Version...

My Hassio Appdaemon say 4.0.1.2

Still I get
message async handler error
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/engineio/asyncio_server.py", line 419, in _trigger_event
    ret = await self.handlers[event](*args)
  File "/usr/lib/python3.8/site-packages/socketio/asyncio_server.py", line 504, in _handle_eio_message
    await self._handle_connect(sid, pkt.namespace)
  File "/usr/lib/python3.8/site-packages/socketio/asyncio_server.py", line 389, in _handle_connect
    success = await self._trigger_event('connect', namespace, sid,
  File "/usr/lib/python3.8/site-packages/socketio/asyncio_server.py", line 478, in _trigger_event
    return await self.namespace_handlers[namespace].trigger_event(
  File "/usr/lib/python3.8/site-packages/socketio/asyncio_namespace.py", line 37, in trigger_event
    ret = await handler(*args)
  File "/usr/lib/python3.8/site-packages/appdaemon/stream.py", line 25, in on_connect
    await self.ADStream.on_connect()
AttributeError: 'ADStream' object has no attribute 'on_connect'

**Comment by ReneTode** [comment]
> My Hassio Appdaemon say 4.0.1.2
that is the addon version.

appdaemon and the addon are 2 different programs.
the addon is there to make it possible to use appdaemon on hassio.
if you look in the logs you will see which version from appdaemon is running.

**Comment by rogerbi** [comment]
got it
[12:17:43] INFO: Starting AppDaemon...
2020-01-31 13:17:51.421182 INFO AppDaemon: AppDaemon Version 4.0.1 starting
Still I get
message async handler error
Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/engineio/asyncio_server.py", line 419, in _trigger_event
ret = await self.handlersevent
File "/usr/lib/python3.8/site-packages/socketio/asyncio_server.py", line 504, in _handle_eio_message
await self._handle_connect(sid, pkt.namespace)
File "/usr/lib/python3.8/site-packages/socketio/asyncio_server.py", line 389, in _handle_connect
success = await self._trigger_event('connect', namespace, sid,
File "/usr/lib/python3.8/site-packages/socketio/asyncio_server.py", line 478, in _trigger_event
return await self.namespace_handlers[namespace].trigger_event(
File "/usr/lib/python3.8/site-packages/socketio/asyncio_namespace.py", line 37, in trigger_event
ret = await handler(*args)
File "/usr/lib/python3.8/site-packages/appdaemon/stream.py", line 25, in on_connect
await self.ADStream.on_connect()
AttributeError: 'ADStream' object has no attribute 'on_connect'

**Comment by acockburn** [comment]
Thanks @rogerbi - I'll take a look at this further.

**Comment by acockburn** [comment]
Yes, I am seeing this too. I'll fix it at the same time as I add socksjs support since they are related - I want to get this into the next release.

**Comment by acockburn** [comment]
This is fixed in dev and will be in 4.0.2

**Comment by Buterbrott** [comment]
I have same error at appdaemon 4.0.3
