### ISSUE TITLE
Empty Dashboard

### ISSUE THREAD

**Issue by schettada** [home-assistant/appdaemon#95]
Hi,

I was able to install the appdaemon and get it connected to Homeassistant without any issues. But when i create a new dashboard and specify some entities in it, the dashboard still comes up as empty. in the debug mode i can see that the appdaemon is able to get the entity data from my home assistant without any errors.

Conf############
sirius:dashboards schettada$ cat Main.dash 
#
# Main arguments, all optional
#
title: Main Panel
widget_dimensions: [120, 120]
widget_size: [1, 1]
widget_margins: [5, 5]
columns: 2
global_parameters:
    use_comma: 0
    precision: 1
    use_hass_icon: 1
layout:
    - sensor.pws_temp_c, sensor.pws_location
sirius:dashboards schettada$ 

sirius:conf schettada$ cat appdaemon.yaml 
AppDaemon:
  logfile: STDOUT
  errorfile: STDERR
  threads: 10
  disable_apps: 1
HASS:
  ha_url: https://rigel.schettada.net
  ha_key: xyz
HADashboard:
  dash_url: http://sirius.schettada.net:5050
  dash_force_compile: 1
# Apps
hello_world:
  module: hello
  class: HelloWorld

sirius:conf schettada$ 

Debug############
2017-07-22 15:44:30.487298 DEBUG Sending data to 0 dashes: {'data': {'old_state': {'last_changed': '2017-07-22T11:50:14.467032+00:00', 'state': 'above_horizon', 'entity_id': 'sun.sun', 'attributes': {'next_dusk': '2017-07-23T02:53:02+00:00', 'elevation': 42.63, 'azimuth': 99.03, 'next_dawn': '2017-07-23T11:20:10+00:00', 'next_setting': '2017-07-23T02:22:03+00:00', 'next_rising': '2017-07-23T11:51:03+00:00', 'next_midnight': '2017-07-23T07:06:11+00:00', 'friendly_name': 'Sun', 'icon': 'mdi:weather-sunny', 'next_noon': '2017-07-22T19:06:08+00:00'}, 'last_updated': '2017-07-22T15:43:30.460770+00:00'}, 'entity_id': 'sun.sun', 'new_state': {'last_changed': '2017-07-22T11:50:14.467032+00:00', 'state': 'above_horizon', 'entity_id': 'sun.sun', 'attributes': {'next_dusk': '2017-07-23T02:53:02+00:00', 'elevation': 42.82, 'azimuth': 99.22, 'next_dawn': '2017-07-23T11:20:10+00:00', 'next_setting': '2017-07-23T02:22:03+00:00', 'next_rising': '2017-07-23T11:51:03+00:00', 'next_midnight': '2017-07-23T07:06:11+00:00', 'friendly_name': 'Sun', 'icon': 'mdi:weather-sunny', 'next_noon': '2017-07-22T19:06:08+00:00'}, 'last_updated': '2017-07-22T15:44:30.461486+00:00'}}, 'event_type': 'state_changed', 'time_fired': '2017-07-22T15:44:30.461612+00:00', 'origin': 'LOCAL'}
2017-07-22 15:44:40.495212 DEBUG Event type:state_changed:
2017-07-22 15:44:40.495374 DEBUG {'old_state': {'last_changed': '2017-07-22T15:44:09.491857+00:00', 'state': '5 days, 23:02:09.489272', 'entity_id': 'sensor.since_last_boot', 'attributes': {'unit_of_measurement': '', 'friendly_name': 'UpTime', 'icon': 'mdi:clock'}, 'last_updated': '2017-07-22T15:44:09.491857+00:00'}, 'entity_id': 'sensor.since_last_boot', 'new_state': {'last_changed': '2017-07-22T15:44:40.477028+00:00', 'state': '5 days, 23:02:40.474858', 'entity_id': 'sensor.since_last_boot', 'attributes': {'unit_of_measurement': '', 'friendly_name': 'UpTime', 'icon': 'mdi:clock'}, 'last_updated': '2017-07-22T15:44:40.477028+00:00'}}
2017-07-22 15:44:40.495469 DEBUG Entity ID:sensor.since_last_boot:
2017-07-22 15:44:40.495625 DEBUG Sending data to 0 dashes: {'data': {'old_state': {'last_changed': '2017-07-22T15:44:09.491857+00:00', 'state': '5 days, 23:02:09.489272', 'entity_id': 'sensor.since_last_boot', 'attributes': {'unit_of_measurement': '', 'friendly_name': 'UpTime', 'icon': 'mdi:clock'}, 'last_updated': '2017-07-22T15:44:09.491857+00:00'}, 'entity_id': 'sensor.since_last_boot', 'new_state': {'last_changed': '2017-07-22T15:44:40.477028+00:00', 'state': '5 days, 23:02:40.474858', 'entity_id': 'sensor.since_last_boot', 'attributes': {'unit_of_measurement': '', 'friendly_name': 'UpTime', 'icon': 'mdi:clock'}, 'last_updated': '2017-07-22T15:44:40.477028+00:00'}}, 'event_type': 'state_changed', 'time_fired': '2017-07-22T15:44:40.477160+00:00', 'origin': 'LOCAL'}
2017-07-22 15:45:01.481425 DEBUG Event type:state_changed:
2017-07-22 15:45:01.481576 DEBUG {'old_state': {'last_changed': '2017-07-22T15:44:01.460303+00:00', 'state': '2017-07-22, 09:44', 'entity_id': 'sensor.date__time', 'attributes': {'friendly_name': 'Date & Time', 'icon': 'mdi:calendar-clock'}, 'last_updated': '2017-07-22T15:44:01.460303+00:00'}, 'entity_id': 'sensor.date__time', 'new_state': {'last_changed': '2017-07-22T15:45:01.459215+00:00', 'state': '2017-07-22, 09:45', 'entity_id': 'sensor.date__time', 'attributes': {'friendly_name': 'Date & Time', 'icon': 'mdi:calendar-clock'}, 'last_updated': '2017-07-22T15:45:01.459215+00:00'}}
2017-07-22 15:45:01.481681 DEBUG Entity ID:sensor.date__time:
2017-07-22 15:45:01.481794 DEBUG Sending data to 0 dashes: {'data': {'old_state': {'last_changed': '2017-07-22T15:44:01.460303+00:00', 'state': '2017-07-22, 09:44', 'entity_id': 'sensor.date__time', 'attributes': {'friendly_name': 'Date & Time', 'icon': 'mdi:calendar-clock'}, 'last_updated': '2017-07-22T15:44:01.460303+00:00'}, 'entity_id': 'sensor.date__time', 'new_state': {'last_changed': '2017-07-22T15:45:01.459215+00:00', 'state': '2017-07-22, 09:45', 'entity_id': 'sensor.date__time', 'attributes': {'friendly_name': 'Date & Time', 'icon': 'mdi:calendar-clock'}, 'last_updated': '2017-07-22T15:45:01.459215+00:00'}}, 'event_type': 'state_changed', 'time_fired': '2017-07-22T15:45:01.459322+00:00', 'origin': 'LOCAL'}
2017-07-22 15:45:01.482849 DEBUG Event type:state_changed:
2017-07-22 15:45:01.482949 DEBUG {'old_state': {'last_changed': '2017-07-22T15:44:01.463534+00:00', 'state': '09:44', 'entity_id': 'sensor.time', 'attributes': {'friendly_name': 'Time', 'icon': 'mdi:clock'}, 'last_updated': '2017-07-22T15:44:01.463534+00:00'}, 'entity_id': 'sensor.time', 'new_state': {'last_changed': '2017-07-22T15:45:01.462468+00:00', 'state': '09:45', 'entity_id': 'sensor.time', 'attributes': {'friendly_name': 'Time', 'icon': 'mdi:clock'}, 'last_updated': '2017-07-22T15:45:01.462468+00:00'}}
2017-07-22 15:45:01.483103 DEBUG Entity ID:sensor.time:
2017-07-22 15:45:01.483513 DEBUG Sending data to 0 dashes: {'data': {'old_state': {'last_changed': '2017-07-22T15:44:01.463534+00:00', 'state': '09:44', 'entity_id': 'sensor.time', 'attributes': {'friendly_name': 'Time', 'icon': 'mdi:clock'}, 'last_updated': '2017-07-22T15:44:01.463534+00:00'}, 'entity_id': 'sensor.time', 'new_state': {'last_changed': '2017-07-22T15:45:01.462468+00:00', 'state': '09:45', 'entity_id': 'sensor.time', 'attributes': {'friendly_name': 'Time', 'icon': 'mdi:clock'}, 'last_updated': '2017-07-22T15:45:01.462468+00:00'}}, 'event_type': 'state_changed', 'time_fired': '2017-07-22T15:45:01.462569+00:00', 'origin': 'LOCAL'}

**Comment by acockburn** [comment]
Are there any errors in your Java console?

**Comment by schettada** [comment]
yup i do.


this looks to be a warning :

jQuery.Deferred exception: Cannot assign to read only property 'width' of object '#<ClientRect>' TypeError: Cannot assign to read only property 'width' of object '#<ClientRect>'
    at Coords.fn.set (http://sirius.schettada.net:5050/javascript/jquery.gridster.js:58:29)
    at Coords.fn.init (http://sirius.schettada.net:5050/javascript/jquery.gridster.js:48:14)
    at new Coords (http://sirius.schettada.net:5050/javascript/jquery.gridster.js:39:14)
    at r.fn.init.$.fn.coords (http://sirius.schettada.net:5050/javascript/jquery.gridster.js:123:19)
    at Gridster.fn.register_widget (http://sirius.schettada.net:5050/javascript/jquery.gridster.js:2082:26)
    at Gridster.fn.add_widget (http://sirius.schettada.net:5050/javascript/jquery.gridster.js:1336:8)
    at HTMLDocument.<anonymous> (http://sirius.schettada.net:5050/compiled_javascript/default/main_init.js:18:18)
    at j (http://sirius.schettada.net:5050/javascript/jquery-3.1.1.min.js:2:29948)
    at k (http://sirius.schettada.net:5050/javascript/jquery-3.1.1.min.js:2:30262) undefined
r.Deferred.exceptionHook @ jquery-3.1.1.min.js:2


and this is an error:

Uncaught TypeError: Cannot assign to read only property 'width' of object '#<ClientRect>'
    at Coords.fn.set (jquery.gridster.js:58)
    at Coords.fn.init (jquery.gridster.js:48)
    at new Coords (jquery.gridster.js:39)
    at r.fn.init.$.fn.coords (jquery.gridster.js:123)
    at Gridster.fn.register_widget (jquery.gridster.js:2082)
    at Gridster.fn.add_widget (jquery.gridster.js:1336)
    at HTMLDocument.<anonymous> (main_init.js:18)
    at j (jquery-3.1.1.min.js:2)
    at k (jquery-3.1.1.min.js:2)





________________________________

**Comment by schettada** [comment]
More of the error.

Uncaught TypeError: Cannot assign to read only property 'width' of object '#<ClientRect>'
    at Coords.fn.set (jquery.gridster.js:58)
    at Coords.fn.init (jquery.gridster.js:48)
    at new Coords (jquery.gridster.js:39)
    at r.fn.init.$.fn.coords (jquery.gridster.js:123)
    at Gridster.fn.register_widget (jquery.gridster.js:2082)
    at Gridster.fn.add_widget (jquery.gridster.js:1336)
    at HTMLDocument.<anonymous> (main_init.js:18)
    at j (jquery-3.1.1.min.js:2)
    at k (jquery-3.1.1.min.js:2)
fn.set @ jquery.gridster.js:58
fn.init @ jquery.gridster.js:48
Coords @ jquery.gridster.js:39
$.fn.coords @ jquery.gridster.js:123
fn.register_widget @ jquery.gridster.js:2082
fn.add_widget @ jquery.gridster.js:1336
(anonymous) @ main_init.js:18
j @ jquery-3.1.1.min.js:2
k @ jquery-3.1.1.min.js:2

**Comment by acockburn** [comment]
What version of AppDaemon are you running?

**Comment by schettada** [comment]
sirius:conf schettada$ docker logs -f --tail 20 appdaemon
2017-07-22 15:38:59.355496 INFO AppDaemon Version 2.0.7 starting
2017-07-22 15:38:59.355754 INFO Configuration read from: /conf/appdaemon.yaml
2017-07-22 15:38:59.652083 INFO Got initial state
2017-07-22 15:38:59.656481 INFO Loading Module: /conf/apps/hello.py
2017-07-22 15:38:59.661224 INFO Loading Object hello_world using class HelloWorld from module hello
2017-07-22 15:38:59.694281 INFO hello_world: Hello from AppDaemon
2017-07-22 15:38:59.695973 INFO hello_world: You are now ready to run Apps!
2017-07-22 15:38:59.696128 INFO App initialization complete
2017-07-22 15:38:59.696448 INFO Starting dashboard
2017-07-22 15:38:59.804036 INFO Connected to Home Assistant 0.49.0
sirius:conf schettada$

**Comment by acockburn** [comment]
I can't tell from the layout if you have any errors in your dash file - can you open a thread in the forum please and use the formatting function so that the indentation shows up correctly.

**Comment by schettada** [comment]
i'm assuming in the HA forum for dashboard?

**Comment by schettada** [comment]
its attached to this email if you can open it.


________________________________

**Comment by acockburn** [comment]
HA Forum please - the attachment didn't make it through

**Comment by schettada** [comment]
https://community.home-assistant.io/t/empty-dashboard-with-appdaemon/22306


________________________________
